/*
 * File: app/view/Engineer/EngElevatorFile_Add.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Engineer.EngElevatorFile_Add', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.field.Hidden',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.field.TextArea',
        'Ext.Img',
        'Ext.Label',
        'Ext.ActionSheet',
        'Ext.Spacer'
    ],

    config: {
        id: 'EngElevatorFile_Add',
        itemId: 'EngElevatorFile_Add',
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                id: 'ELevatorFile_Tbr',
                title: '新增电梯档案',
                items: [
                    {
                        xtype: 'button',
                        id: 'ElevatorFile_BtnReturn',
                        itemId: 'ElevatorFile_BtnReturn',
                        iconCls: 'fa fa-chevron-left'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                flex: 1,
                cls: 'liftnet-tabbar-two',
                items: [
                    {
                        xtype: 'container',
                        title: '电梯信息',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                flex: 1,
                                cls: [
                                    'liftnet-form-info',
                                    'liftnet-font-size14',
                                    'liftnet-lineHeight34'
                                ],
                                id: 'ElevatorFile_Info_Form',
                                scrollable: true,
                                items: [
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_prono',
                                        itemId: 'ElevatorFile_prono',
                                        label: '设备注册码',
                                        labelWidth: '40%',
                                        name: 'prono',
                                        required: true,
                                        placeHolder: '请输入设备注册码'
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'ElevatorFile_NowProno',
                                        itemId: 'ElevatorFile_NowProno'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_equno',
                                        itemId: 'ElevatorFile_equno',
                                        label: '使用登记号',
                                        labelWidth: '40%',
                                        name: 'equno',
                                        placeHolder: '请输入使用登记号'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_elevatorno',
                                        label: '出厂编号',
                                        name: 'elevatorno',
                                        placeHolder: '请输入出厂编号'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_r3',
                                        itemId: 'ElevatorFile_r3',
                                        label: '梯号',
                                        name: 'r3',
                                        placeHolder: '请输入梯号'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        cls: 'x-field-picker',
                                        id: 'ElevatorFile_typeid',
                                        itemId: 'ElevatorFile_typeid',
                                        label: '电梯分类',
                                        labelWidth: '40%',
                                        name: 'typeid',
                                        required: true,
                                        placeHolder: '请选择电梯分类',
                                        displayField: 'typename',
                                        store: 'eng_lifttypelist',
                                        valueField: 'typeid'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        cls: 'x-field-picker',
                                        id: 'ElevatorFile_useplace',
                                        itemId: 'ElevatorFile_useplace',
                                        label: '使用场所',
                                        labelWidth: '40%',
                                        name: 'useplace',
                                        required: true,
                                        placeHolder: '请选择使用场所',
                                        displayField: 'placename',
                                        store: 'eng_placelist',
                                        valueField: 'placeid'
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: 'x-field-search',
                                        id: 'ElevatorFile_elevatorid',
                                        itemId: 'ElevatorFile_elevatorid',
                                        label: '电梯型号',
                                        labelWidth: '40%',
                                        name: 'elevatorname',
                                        required: true,
                                        placeHolder: '请选择电梯型号',
                                        readOnly: true,
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    var me = this;
                                                    me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'ElevatorFile_elevator',
                                        itemId: 'ElevatorFile_elevator',
                                        name: 'elevatorid'
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: 'x-field-search',
                                        id: 'ElevatorFile_r1',
                                        itemId: 'ElevatorFile_r1',
                                        label: '电梯品牌',
                                        labelWidth: '40%',
                                        name: 'r1name',
                                        required: true,
                                        placeHolder: '请选择电梯品牌',
                                        readOnly: true,
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    var me = this;
                                                    me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'ElevatorFile_r1id',
                                        itemId: 'ElevatorFile_r1id',
                                        name: 'r1'
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        cls: 'x-field-datetime',
                                        id: 'ElevatorFile_leafacdate',
                                        itemId: 'ElevatorFile_leafacdate',
                                        label: '出厂日期',
                                        labelWidth: '35%',
                                        name: 'leafacdate',
                                        required: true,
                                        placeHolder: '请选择出厂日期',
                                        dateFormat: 'Y-m-d',
                                        picker: {
                                            hideOnMaskTap: true,
                                            slotOrder: [
                                                'year',
                                                'month',
                                                'day'
                                            ],
                                            yearFrom: 1990,
                                            yearTo: 2020,
                                            doneButton: '确定',
                                            cancelButton: '取消'
                                        }
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        cls: 'x-field-datetime',
                                        id: 'ElevatorFile_r7',
                                        itemId: 'ElevatorFile_r7',
                                        label: '电梯年检日期',
                                        labelWidth: '45%',
                                        name: 'r7',
                                        required: true,
                                        placeHolder: '请选择电梯年检日期',
                                        dateFormat: 'Y-m-d',
                                        picker: {
                                            hideOnMaskTap: true,
                                            slotOrder: [
                                                'year',
                                                'month',
                                                'day'
                                            ],
                                            yearFrom: 1990,
                                            yearTo: 2020,
                                            doneButton: '确定',
                                            cancelButton: '取消'
                                        }
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        cls: 'x-field-datetime',
                                        id: 'ElevatorFile_r8',
                                        itemId: 'ElevatorFile_r8',
                                        label: '电梯下次年检日期',
                                        labelWidth: '52%',
                                        name: 'r8',
                                        required: true,
                                        placeHolder: '请选择电梯下次年检日期',
                                        dateFormat: 'Y-m-d',
                                        picker: {
                                            hideOnMaskTap: true,
                                            slotOrder: [
                                                'year',
                                                'month',
                                                'day'
                                            ],
                                            yearFrom: 1990,
                                            yearTo: 2020,
                                            doneButton: '确定',
                                            cancelButton: '取消'
                                        }
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_zzl',
                                        itemId: 'ElevatorFile_zzl',
                                        label: '载重量(kg)',
                                        name: 'zzl',
                                        placeHolder: '请输入载重量'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_speed',
                                        itemId: 'ElevatorFile_speed',
                                        label: '速度(m/s)',
                                        name: 'speed',
                                        placeHolder: '请输入速度'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_floor',
                                        itemId: 'ElevatorFile_floor',
                                        label: '层',
                                        name: 'floor',
                                        placeHolder: '请输入层'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_stage',
                                        itemId: 'ElevatorFile_stage',
                                        label: '站',
                                        name: 'stage',
                                        placeHolder: '请输入站'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'Elevator_door',
                                        itemId: 'Elevator_door',
                                        label: '门',
                                        name: 'door',
                                        placeHolder: '请输入门'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'Elevator_high',
                                        itemId: 'Elevator_high',
                                        label: '提升高度',
                                        name: 'high',
                                        placeHolder: '请输入提升高度'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_fwlc',
                                        itemId: 'ElevatorFile_fwlc',
                                        label: '倾斜角',
                                        name: 'fwlc',
                                        placeHolder: '请输入切斜角'
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: 'x-field-search',
                                        id: 'ElevatorFile_projectname',
                                        itemId: 'ElevatorFile_projectname',
                                        label: '关联项目',
                                        labelWidth: '40%',
                                        name: 'r12name',
                                        placeHolder: '请选择关联项目',
                                        readOnly: true,
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    var me = this;
                                                    me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'ElevatorFile_r12',
                                        itemId: 'ElevatorFile_r12',
                                        name: 'r12'
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'ElevatorFile_r13',
                                        itemId: 'ElevatorFile_r13',
                                        name: 'r13'
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'ElevatorFile_detailrowid',
                                        itemId: 'ElevatorFile_detailrowid',
                                        name: 'detailrowid'
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: 'x-field-search',
                                        id: 'ElevatorFile_domainidStr',
                                        itemId: 'ElevatorFile_domainidStr',
                                        label: '区域',
                                        name: 'domainidstr',
                                        placeHolder: '请选择区域',
                                        readOnly: true,
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    var me = this;
                                                    me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'ElevatorFile_domainid',
                                        itemId: 'ElevatorFile_domainid',
                                        name: 'domainid'
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: 'x-field-search',
                                        id: 'ElevatorFile_provinciallevelidStr',
                                        itemId: 'ElevatorFile_provinciallevelidStr',
                                        label: '省份',
                                        name: 'provinciallevelidstr',
                                        placeHolder: '请选择省份',
                                        readOnly: true,
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    var me = this;
                                                    me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'ElevatorFile_provinciallevelid',
                                        itemId: 'ElevatorFile_provinciallevelid',
                                        name: 'provinciallevelid'
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: 'x-field-search',
                                        id: 'ElevatorFile_citylevelidStr',
                                        itemId: 'ElevatorFile_citylevelidStr',
                                        label: '所在市',
                                        name: 'citylevelidstr',
                                        placeHolder: '请选择所在市',
                                        readOnly: true,
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    var me = this;
                                                    me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'ElevatorFile_citylevelid',
                                        itemId: 'ElevatorFile_citylevelid',
                                        name: 'citylevelid'
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: 'x-field-search',
                                        id: 'ElevatorFile_countylevelidStr',
                                        itemId: 'ElevatorFile_countylevelidStr',
                                        label: '县区',
                                        name: 'countylevelidstr',
                                        placeHolder: '请选择县区',
                                        readOnly: true,
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    var me = this;
                                                    me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'hiddenfield',
                                        id: 'ElevatorFile_countylevelid',
                                        itemId: 'ElevatorFile_countylevelid',
                                        name: 'countylevelid'
                                    },
                                    {
                                        xtype: 'textareafield',
                                        id: 'ElevatorFile_eleuseaddress',
                                        itemId: 'ElevatorFile_eleuseaddress',
                                        label: '项目地址',
                                        name: 'eleuseaddress',
                                        placeHolder: '请选择项目地址'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_liftloaction',
                                        itemId: 'ElevatorFile_liftloaction',
                                        label: '电梯位置描述',
                                        labelWidth: '40%',
                                        name: 'liftloaction',
                                        placeHolder: '请输入电梯位置描述'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_userunitId',
                                        itemId: 'ElevatorFile_userunitId',
                                        label: '用户单位',
                                        name: 'userunitid',
                                        placeHolder: '请输入用户单位'
                                    },
                                    {
                                        xtype: 'textareafield',
                                        id: 'ElevatorFile_useraddress',
                                        itemId: 'ElevatorFile_useraddress',
                                        label: '用户单位地址',
                                        labelWidth: '40%',
                                        name: 'useraddress',
                                        placeHolder: '请输入用户单位地址'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_userlinkman',
                                        itemId: 'ElevatorFile_userlinkman',
                                        label: '联系人',
                                        name: 'userlinkman',
                                        placeHolder: '请输入联系人'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_userlinkphone',
                                        itemId: 'ElevatorFile_userlinkphone',
                                        label: '联系电话',
                                        name: 'userlinkphone',
                                        placeHolder: '请输入联系电话'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_allowno',
                                        itemId: 'ElevatorFile_allowno',
                                        label: '施工许可证号',
                                        labelWidth: '40%',
                                        name: 'allowno',
                                        placeHolder: '请输入施工许可证号'
                                    },
                                    {
                                        xtype: 'textfield',
                                        cls: 'x-field-search',
                                        id: 'ElevatorFie_r2',
                                        itemId: 'ElevatorFie_r2',
                                        label: '坐标',
                                        name: 'r2',
                                        placeHolder: '请选择坐标',
                                        readOnly: true,
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    var me = this;
                                                    me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        cls: 'x-field-datetime',
                                        id: 'ElevatorFile_finishdate',
                                        itemId: 'ElevatorFile_finishdate',
                                        label: '竣工日期',
                                        labelWidth: '35%',
                                        name: 'finishdate',
                                        placeHolder: '请选择竣工日期',
                                        dateFormat: 'Y-m-d',
                                        picker: {
                                            hideOnMaskTap: true,
                                            slotOrder: [
                                                'year',
                                                'month',
                                                'day'
                                            ],
                                            yearFrom: 1990,
                                            yearTo: 2020,
                                            doneButton: '确定',
                                            cancelButton: '取消'
                                        }
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        cls: 'x-field-datetime',
                                        id: 'ElevatorFile_firstuseliftdate',
                                        itemId: 'ElevatorFile_firstuseliftdate',
                                        label: '首次使用日期',
                                        labelWidth: '45%',
                                        name: 'firstuseliftdate',
                                        placeHolder: '请选择首次使用日期',
                                        dateFormat: 'Y-m-d',
                                        picker: {
                                            hideOnMaskTap: true,
                                            slotOrder: [
                                                'year',
                                                'month',
                                                'day'
                                            ],
                                            yearFrom: 1990,
                                            yearTo: 2020,
                                            doneButton: '确定',
                                            cancelButton: '取消'
                                        }
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        cls: 'x-field-datetime',
                                        id: 'ElevatorFile_speedcheckdate',
                                        itemId: 'ElevatorFile_speedcheckdate',
                                        label: '限速器年检日期',
                                        labelWidth: '50%',
                                        name: 'speedcheckdate',
                                        placeHolder: '请选择限速器年检日期',
                                        dateFormat: 'Y-m-d',
                                        picker: {
                                            hideOnMaskTap: true,
                                            slotOrder: [
                                                'year',
                                                'month',
                                                'day'
                                            ],
                                            yearFrom: 1990,
                                            yearTo: 2020,
                                            doneButton: '确定',
                                            cancelButton: '取消'
                                        }
                                    },
                                    {
                                        xtype: 'datepickerfield',
                                        cls: 'x-field-datetime',
                                        id: 'ElevatorFile_speednextcheckdate',
                                        itemId: 'ElevatorFile_speednextcheckdate',
                                        label: '下一次年检日期',
                                        labelWidth: '50%',
                                        name: 'speednextcheckdate',
                                        placeHolder: '请选择下一次年检日期',
                                        dateFormat: 'Y-m-d',
                                        picker: {
                                            hideOnMaskTap: true,
                                            slotOrder: [
                                                'year',
                                                'month',
                                                'day'
                                            ],
                                            yearFrom: 1990,
                                            yearTo: 2020,
                                            doneButton: '确定',
                                            cancelButton: '取消'
                                        }
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_r9',
                                        itemId: 'ElevatorFile_r9',
                                        label: '到期预警天数',
                                        labelWidth: '40%',
                                        name: 'r9',
                                        placeHolder: '请输入到期预警天数'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        cls: 'x-field-picker',
                                        id: 'ElevatorFile_kmfs',
                                        itemId: 'ElevatorFile_kmfs',
                                        label: '开门方式',
                                        labelWidth: '35%',
                                        name: 'kmfs',
                                        placeHolder: '请选择开门方式',
                                        displayField: 'dswingname',
                                        store: 'eng_kmfslist',
                                        valueField: 'dswingid'
                                    },
                                    {
                                        xtype: 'textareafield',
                                        id: 'ElevatorFile_openremark',
                                        itemId: 'ElevatorFile_openremark',
                                        label: '开门方式备注',
                                        labelWidth: '40%',
                                        name: 'openremark',
                                        placeHolder: '请输入开门方式备注'
                                    },
                                    {
                                        xtype: 'selectfield',
                                        cls: 'x-field-picker',
                                        id: 'ElevatorFile_contype',
                                        itemId: 'ElevatorFile_contype',
                                        label: '控制方式',
                                        labelWidth: '40%',
                                        name: 'contype',
                                        placeHolder: '请选择控制方式',
                                        displayField: 'controlname',
                                        store: 'eng_kzfslist',
                                        valueField: 'controlid',
                                        listeners: [
                                            {
                                                fn: function(component, eOpts) {
                                                    var me = this;
                                                    me.element.on('change', function(e, t) { me.fireEvent('change', me, e, t); }, me);
                                                },
                                                event: 'initialize'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'textfield',
                                        hidden: true,
                                        id: 'ElevatorFile_controlnum',
                                        itemId: 'ElevatorFile_controlnum',
                                        label: '群控台数',
                                        name: 'controlnum',
                                        placeHolder: '请输入群控台数'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_r4',
                                        itemId: 'ElevatorFile_r4',
                                        label: '保管人姓名',
                                        labelWidth: '40%',
                                        name: 'r4',
                                        placeHolder: '请输入保管人姓名'
                                    },
                                    {
                                        xtype: 'textfield',
                                        id: 'ElevatorFile_r5',
                                        itemId: 'ElevatorFile_r5',
                                        label: '保管人联系电话',
                                        labelWidth: '45%',
                                        name: 'r5',
                                        placeHolder: '请输入保管人联系电话'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: [
                                    'liftnet-button',
                                    'liftnet-button-three'
                                ],
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'button',
                                        flex: 1,
                                        id: 'ElevatorFile_SaveBtn',
                                        itemId: 'ElevatorFile_SaveBtn',
                                        text: '保存'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: '附件',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'panel',
                                flex: 1,
                                padding: '20 5 0 5',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        padding: '15 0 0 0',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        height: 85,
                                                        id: 'ElevatortFile_Photo_1',
                                                        itemId: 'ElevatorFile_Photo_camera',
                                                        margin: '0 2 0 0',
                                                        src: 'resources/images/camera.png'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        cls: [
                                                            'liftnet-font-size14',
                                                            'liftnet-fontColor-blue'
                                                        ],
                                                        html: '描述....',
                                                        id: 'ElevatorFile_Remark_1',
                                                        margin: '10 10 0 10',
                                                        style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        height: 85,
                                                        id: 'ElevatortFile_Photo_2',
                                                        margin: '0 2 0 2',
                                                        src: 'resources/images/notPhoto.png'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        cls: [
                                                            'liftnet-font-size14',
                                                            'liftnet-fontColor-blue'
                                                        ],
                                                        html: '描述....',
                                                        id: 'ElevatorFile_Remark_2',
                                                        margin: '10 10 0 10',
                                                        style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        height: 85,
                                                        id: 'ElevatortFile_Photo_3',
                                                        margin: '0 2 0 2',
                                                        src: 'resources/images/notPhoto.png'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        cls: [
                                                            'liftnet-font-size14',
                                                            'liftnet-fontColor-blue'
                                                        ],
                                                        html: '描述....',
                                                        id: 'ElevatorFile_Remark_3',
                                                        margin: '10 10 0 10',
                                                        style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        height: 85,
                                                        id: 'ElevatortFile_Photo_4',
                                                        margin: '0 2 0 0',
                                                        src: 'resources/images/notPhoto.png'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        cls: [
                                                            'liftnet-font-size14',
                                                            'liftnet-fontColor-blue'
                                                        ],
                                                        html: '描述....',
                                                        id: 'ElevatorFile_Remark_4',
                                                        margin: '10 10 0 10',
                                                        style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        height: 85,
                                                        id: 'ElevatortFile_Photo_5',
                                                        margin: '0 2 0 2',
                                                        src: 'resources/images/notPhoto.png'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        cls: [
                                                            'liftnet-font-size14',
                                                            'liftnet-fontColor-blue'
                                                        ],
                                                        html: '描述....',
                                                        id: 'ElevatorFile_Remark_5',
                                                        margin: '10 10 0 10',
                                                        style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'container',
                                                flex: 1,
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        height: 85,
                                                        id: 'ElevatortFile_Photo_6',
                                                        margin: '0 2 0 2',
                                                        src: 'resources/images/notPhoto.png'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        cls: [
                                                            'liftnet-font-size14',
                                                            'liftnet-fontColor-blue'
                                                        ],
                                                        html: '描述....',
                                                        id: 'ElevatorFile_Remark_6',
                                                        margin: '10 10 0 10',
                                                        style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'actionsheet',
                                        hidden: true,
                                        id: 'ElevatorFile_ActionSheet',
                                        itemId: 'ElevatorFile_ActionSheet',
                                        hideOnMaskTap: true,
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'button',
                                                id: 'ElevatorFile_Camera',
                                                itemId: 'ElevatorFile_Camera',
                                                width: 110,
                                                text: '相机'
                                            },
                                            {
                                                xtype: 'spacer',
                                                width: 70
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'ElevatorFile_Album',
                                                itemId: 'ElevatorFile_Album',
                                                width: 110,
                                                text: '相册'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                docked: 'bottom',
                                height: 100,
                                hidden: true,
                                margin: '5 5 0 5',
                                layout: 'hbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        items: [
                                            {
                                                xtype: 'container',
                                                margin: '0 auto',
                                                items: [
                                                    {
                                                        xtype: 'image',
                                                        height: 64,
                                                        width: 64,
                                                        src: 'resources/images/camera.png'
                                                    },
                                                    {
                                                        xtype: 'label',
                                                        cls: [
                                                            'liftnet-font-size14',
                                                            'liftnet-fontColor-darkGray'
                                                        ],
                                                        html: '拍照',
                                                        margin: '5 0 0 0',
                                                        padding: '0 0 0 15'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        items: [
                                            {
                                                xtype: 'image',
                                                height: 64,
                                                width: 64,
                                                src: 'resources/images/album.png'
                                            },
                                            {
                                                xtype: 'label',
                                                cls: [
                                                    'liftnet-font-size14',
                                                    'liftnet-fontColor-darkGray'
                                                ],
                                                html: '相册',
                                                margin: '5 0 0 0',
                                                padding: '0 0 0 15'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'container',
                                        flex: 1
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});