/*
 * File: app/view/Engineer/EngElevatorFile.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Engineer.EngElevatorFile', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.Panel',
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        id: 'EngElevatorFile',
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                title: '电梯档案',
                items: [
                    {
                        xtype: 'button',
                        id: 'EngElevatorFile_BtnReturn',
                        iconCls: 'fa fa-chevron-left',
                        text: ''
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'EngElevatorFile_NewBtn',
                        iconCls: 'ln ln-new',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'formpanel',
                cls: 'liftnet-search-form',
                height: 52,
                items: [
                    {
                        xtype: 'searchfield',
                        cls: 'liftnet-font-size12',
                        id: 'EngElevatorFile_Search',
                        label: '',
                        placeHolder: '注册码、品牌、型号'
                    }
                ]
            },
            {
                xtype: 'list',
                flex: 1,
                cls: 'liftnet-fault-listBox',
                id: 'EngElevatorFile_List',
                disableSelection: true,
                itemTpl: [
                    '<div class="liftnet-Maintenance-TaskRecList" style="height:80px">',
                    '    <div class="liftnet-Maintenance-TaskRecList-left" style="left:14px" >',
                    '        <div class="liftnet-font-size14 {titleColor}">{prono}&nbsp;</div>',
                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{facname}&nbsp;</div>',
                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{useraddress}&nbsp;</div>',
                    '    </div>',
                    '    <div class="liftnet-Maintenance-TaskRecList-right" style="padding-top:0px;right:14px">',
                    '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">{equno}&nbsp;</div>',
                    '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">{elevatorid}&nbsp;</div>',
                    '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">{fsd}&nbsp;</div>',
                    '    </div>',
                    '</div>'
                ],
                store: 'eng_elevatorfilequerylist'
            }
        ]
    }

});