/*
 * File: app/view/Engineer/EngFaultRedeployed.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Engineer.EngFaultRedeployed', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.field.Hidden',
        'Ext.Panel',
        'Ext.field.Search'
    ],

    config: {
        id: 'Redeployed',
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                id: 'EngFaultRedeployed_Tbar',
                title: '请选择维修人员',
                items: [
                    {
                        xtype: 'button',
                        id: 'EngFaultRedeployed_BtnReturn',
                        itemId: 'EngFaultRedeployed_BtnReturn',
                        iconCls: 'fa fa-chevron-left'
                    }
                ]
            },
            {
                xtype: 'list',
                flex: 1,
                id: 'EngFaultRedeployed_List',
                itemId: 'EngFaultRedeployed_List',
                itemTpl: [
                    '<div class="liftnet-font-size14 liftnet-fontColor-darkGray">{username}({linkphone})</div>',
                    '    <div class="liftnet-font-size12 liftnet-fontColor-gray">{storagename}</div>'
                ],
                pressedCls: '',
                store: 'common_sxpglist',
                items: [
                    {
                        xtype: 'hiddenfield',
                        id: 'Redeployed_trno',
                        itemId: 'Redeployed_trno'
                    },
                    {
                        xtype: 'hiddenfield',
                        id: 'Redeployed_flg',
                        itemId: 'Redeployed_flg'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: [
                    'liftnet-button',
                    'liftnet-button-three'
                ],
                docked: 'bottom',
                layout: 'hbox',
                items: [
                    {
                        xtype: 'button',
                        flex: 1,
                        id: 'Redeployed_BtnOK',
                        itemId: 'Redeployed_BtnOK',
                        text: '确认'
                    }
                ]
            }
        ]
    }

});