/*
 * File: app/view/Engineer/EngFirstCheckCheckUser2.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Engineer.EngFirstCheckCheckUser2', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.Panel',
        'Ext.field.Select',
        'Ext.field.Hidden'
    ],

    config: {
        id: 'EngFirstCheckCheckUser2',
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                title: '检验人员',
                items: [
                    {
                        xtype: 'button',
                        id: 'EngFirstCheckCheckUser2_BtnReturn',
                        iconCls: 'fa fa-chevron-left',
                        text: ''
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'EngFirstCheckCheckUser2_BtnDelete',
                        iconAlign: 'right',
                        iconCls: 'delete',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'formpanel',
                flex: 1,
                cls: [
                    'liftnet-form-info',
                    'liftnet-font-size14',
                    'liftnet-lineHeight34'
                ],
                id: 'EngFirstCheckCheckUser2_Form',
                itemId: 'EngFirstCheckCheckUser2_Form',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'EngFirstCheckCheckUser2_username',
                        itemId: 'EngFirstCheckCheckUser2_username',
                        label: '检验人员',
                        name: 'username',
                        required: true,
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    var me = this;
                                    me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'selectfield',
                        id: 'EngFirstCheckCheckUser2_usertypeid',
                        itemId: 'EngFirstCheckCheckUser2_usertypeid',
                        label: '类别',
                        name: 'usertype',
                        required: true,
                        displayField: 'usertypename',
                        store: 'eng_checkuser_usertype',
                        valueField: 'usertype'
                    },
                    {
                        xtype: 'hiddenfield',
                        name: 'department'
                    },
                    {
                        xtype: 'hiddenfield',
                        name: 'departmentid'
                    },
                    {
                        xtype: 'hiddenfield',
                        name: 'userid'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: [
                    'liftnet-button',
                    'liftnet-button-one'
                ],
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        cls: 'liftnet-no-border',
                        html: '保存',
                        id: 'EngFirstCheckCheckUser2_BtnSave',
                        itemId: 'EngFirstCheckCheckUser2_BtnSave',
                        text: ''
                    }
                ]
            }
        ]
    }

});