/*
 * File: app/view/Engineer/EngFaultReportReasonAdd.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Engineer.EngFaultReportReasonAdd', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.Panel',
        'Ext.field.TextArea'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                title: '故障原因',
                items: [
                    {
                        xtype: 'button',
                        id: 'ReasonAdd_BtnReturn',
                        itemId: 'ReasonAdd_BtnReturn',
                        iconCls: 'fa fa-chevron-left'
                    }
                ]
            },
            {
                xtype: 'formpanel',
                flex: 1,
                cls: [
                    'liftnet-form-info',
                    'liftnet-font-size14'
                ],
                id: 'ReasonAdd_form',
                itemId: 'ReasonAdd_form',
                items: [
                    {
                        xtype: 'textareafield',
                        id: 'ReasonAdd_str',
                        itemId: 'ReasonAdd_str',
                        label: '故障原因',
                        name: 'ReasonAdd_str',
                        placeHolder: '请输入故障原因'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: [
                    'liftnet-button',
                    'liftnet-button-one'
                ],
                docked: 'bottom',
                id: 'ReasonAdd_BtnPanel',
                itemId: 'ReasonAdd_BtnPanel',
                items: [
                    {
                        xtype: 'button',
                        docked: 'left',
                        id: 'ReasonAdd_Sub',
                        itemId: 'ReasonAdd_Sub',
                        text: '确定'
                    }
                ]
            }
        ]
    }

});