/*
 * File: app/view/Engineer/EngFault.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Engineer.EngFault', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Label',
        'Ext.field.DatePicker',
        'Ext.picker.Date'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                flex: 1,
                id: 'EngFault',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: 'liftnet-toolbar-other',
                        docked: 'top',
                        title: '维修任务',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'EngFault_ReturnButton',
                                iconCls: 'fa fa-chevron-left'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                hidden: true,
                                id: 'EngFault_BtnAdd',
                                iconCls: 'ln ln-new'
                            }
                        ]
                    },
                    {
                        xtype: 'tabpanel',
                        flex: 1,
                        cls: 'liftnet-tabbar-one',
                        id: 'EngFault_TplList',
                        items: [
                            {
                                xtype: 'container',
                                title: '故障受信',
                                cls: 'liftnet-fault-listBox',
                                itemId: 'EngFault_CtnFaultList',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'formpanel',
                                        cls: 'liftnet-search-form',
                                        height: 52,
                                        id: 'EngFault_SearchForm',
                                        scrollable: false,
                                        items: [
                                            {
                                                xtype: 'searchfield',
                                                cls: 'liftnet-font-size12',
                                                id: 'Enfault_Search',
                                                itemId: 'Enfault_Search',
                                                placeHolder: '项目名称、地址、维修人员'
                                            },
                                            {
                                                xtype: 'button',
                                                cls: [
                                                    'liftnet-font-size12',
                                                    'liftnet-no-border',
                                                    'liftnet-fontColor-darkGray'
                                                ],
                                                docked: 'right',
                                                id: 'EnFault_More',
                                                itemId: 'EnFault_More',
                                                margin: '16 0',
                                                width: 50,
                                                text: '更多'
                                            },
                                            {
                                                xtype: 'button',
                                                cls: [
                                                    'liftnet-font-size12',
                                                    'liftnet-no-border',
                                                    'liftnet-fontColor-darkGray'
                                                ],
                                                docked: 'right',
                                                id: 'Enfault_button',
                                                margin: '16 0',
                                                width: 70,
                                                iconAlign: 'right',
                                                iconCls: 'fa fa-angle-down',
                                                text: '全部'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        flex: 1,
                                        cls: 'liftnet-home-listBox',
                                        id: 'EngFault_ListHotline',
                                        itemId: 'Home_HotLine',
                                        disableSelection: true,
                                        itemTpl: [
                                            '<div class="liftnet-fault-listConBox">',
                                            '	{urgent}',
                                            '	<div class="liftnet-fault-listConBox-left">',
                                            '    	<!--<div class="liftnet-font-size16 {titleColor}">{titleIcon}{trno}{istrap}</div>-->',
                                            '    	<div class="liftnet-font-size12 {titleColor}">{projectname}</div>',
                                            '    	<div class="liftnet-font-size12 liftnet-fontColor-gray">{addr}</div>',
                                            '    	<div class="liftnet-font-size12 liftnet-fontColor-gray">{checkuser}</div>',
                                            '        <div class="liftnet-font-size12 liftnet-fontColor-gray"><i class="fa fa-clock-o"></i> {operdate}</div>',
                                            '    </div>',
                                            '	<div class="liftnet-fault-listConBox-right">',
                                            '    	<div class="liftnet-home-listConBox-state liftnet-font-right liftnet-font-size12 {statusColor}">{state} <i class="fa fa-circle-o"></i></div>',
                                            '    </div>',
                                            '</div>'
                                        ],
                                        pressedCls: ' ',
                                        store: 'sx_sxlist'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                title: '故障报告',
                                itemId: 'EngFault_CtnReportList',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'formpanel',
                                        cls: 'liftnet-search-form',
                                        height: 52,
                                        hidden: true,
                                        id: 'EngFaultReport_SearchForm',
                                        layout: 'hbox',
                                        scrollable: false,
                                        items: [
                                            {
                                                xtype: 'label',
                                                cls: 'liftnet-fontColor-gray',
                                                docked: 'left',
                                                html: '<i class=\'fa fa-calendar\'></i>',
                                                margin: '18 -4 0 8',
                                                width: 20
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                flex: 1,
                                                id: 'EngFaultReport_date1',
                                                inputCls: 'liftnet-font-center',
                                                name: 'date1',
                                                placeHolder: '开始日期',
                                                dateFormat: 'Y-m-d',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    doneButton: '确定',
                                                    cancelButton: '取消'
                                                }
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                flex: 1,
                                                id: 'EngFaultReport_date2',
                                                inputCls: 'liftnet-font-center',
                                                name: 'date2',
                                                placeHolder: '结束日期',
                                                dateFormat: 'Y-m-d',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    doneButton: '确定',
                                                    cancelButton: '取消'
                                                }
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'formpanel',
                                        cls: 'liftnet-search-form',
                                        height: 52,
                                        id: 'EngReport_SearchForm',
                                        scrollable: false,
                                        items: [
                                            {
                                                xtype: 'searchfield',
                                                cls: 'liftnet-font-size12',
                                                id: 'EngReport_Search',
                                                itemId: 'EngReport_Search',
                                                width: '100%',
                                                placeHolder: '项目名称、地址、维修人员'
                                            },
                                            {
                                                xtype: 'button',
                                                cls: [
                                                    'liftnet-font-size12',
                                                    'liftnet-no-border',
                                                    'liftnet-fontColor-darkGray'
                                                ],
                                                docked: 'right',
                                                id: 'EngReport_Button',
                                                itemId: 'EngReport_Button',
                                                margin: '16 0',
                                                width: 70,
                                                iconAlign: 'right',
                                                iconCls: 'fa fa-angle-down',
                                                text: '全部'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        flex: 1,
                                        cls: 'liftnet-fault-listBox',
                                        id: 'EngFault_ListReport',
                                        disableSelection: true,
                                        itemTpl: [
                                            '<div class="liftnet-home-listConBox">',
                                            '	{urgent}',
                                            '	<div class="liftnet-home-listConBox-left">',
                                            '        <div class="liftnet-font-size16 {color}"><i class="ln ln-message2"></i>&nbsp;{rpno}</div>',
                                            '    	<div class="liftnet-font-size12 liftnet-fontColor-gray">{projectname}</div>',
                                            '        <div class="liftnet-font-size12 liftnet-fontColor-gray"><i class="fa fa-clock-o"></i> {rptime}</div>',
                                            '    </div>',
                                            '	<div class="liftnet-home-listConBox-right">',
                                            '    	<div class="liftnet-home-listConBox-state liftnet-font-right liftnet-font-size12 {color}">{state} <i class="fa fa-circle-o"></i></div>',
                                            '    </div>',
                                            '</div>'
                                        ],
                                        pressedCls: ' ',
                                        store: 'sx_reportlist'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});