/*
 * File: app/view/Engineer/EngInsureContractDetail.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Engineer.EngInsureContractDetail', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.field.TextArea',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        id: 'EngInsureContractDetail',
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                title: '保险合同信息',
                items: [
                    {
                        xtype: 'button',
                        id: 'EngInsureContractDetail_BtnReturn',
                        iconCls: 'fa fa-chevron-left',
                        text: ''
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                flex: 1,
                cls: 'liftnet-tabbar-two',
                id: 'EngInsureContractDetail_Tab',
                items: [
                    {
                        xtype: 'container',
                        title: '保险合同',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                flex: 1,
                                cls: [
                                    'liftnet-form-info',
                                    'liftnet-font-size14',
                                    'liftnet-lineHeight34'
                                ],
                                id: 'EngInsureContractDetail_Contract',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        label: '保险合同号',
                                        labelWidth: '40%',
                                        name: 'contractid',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '合同台数',
                                        labelWidth: '40%',
                                        name: 'contractnum',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '合同总额',
                                        labelWidth: '40%',
                                        name: 'contractamt',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '承保单位',
                                        name: 'acceptanceunit',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '保险业务经理',
                                        labelWidth: '40%',
                                        name: 'insurancemanager',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '联系电话',
                                        labelWidth: '40%',
                                        name: 'linkphone',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '开始日期',
                                        labelWidth: '40%',
                                        name: 'insurancestartdate',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '结束日期',
                                        labelWidth: '40%',
                                        name: 'insuranceenddate',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '签订日期',
                                        name: 'signdate',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '理赔电话',
                                        labelWidth: '40%',
                                        name: 'claimsphone',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '创建人',
                                        labelWidth: '40%',
                                        name: 'createmess',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        label: '创建日期',
                                        labelWidth: '40%',
                                        name: 'createdate',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textareafield',
                                        label: '备注',
                                        labelWidth: '40%',
                                        name: 'remark',
                                        readOnly: true
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: '关联合同',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'list',
                                flex: 1,
                                cls: 'liftnet-fault-listBox',
                                id: 'EngInsureContractDetail_Info',
                                disableSelection: true,
                                itemTpl: [
                                    '<div class="liftnet-Maintenance-TaskRecList" style="height:80px">',
                                    '    <div class="liftnet-Maintenance-TaskRecList-left" style="left:14px" >',
                                    '        <div class="liftnet-font-size16 {titleColor}">{contractid}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{projectname}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{projectaddress}&nbsp;</div>',
                                    '    </div>',
                                    '    <div class="liftnet-Maintenance-TaskRecList-right" style="padding-top:0px;right:14px">',
                                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray liftnet-font-right">{custname}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray liftnet-font-right">&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">{nums}&nbsp;台</div>',
                                    '    </div>',
                                    '</div>'
                                ],
                                store: 'eng_insurecontracttabglht'
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: '电梯',
                        layout: 'hbox',
                        items: [
                            {
                                xtype: 'list',
                                flex: 1,
                                cls: 'liftnet-fault-listBox',
                                id: 'EngInsureContractDetail_ElevatorList',
                                disableSelection: true,
                                itemTpl: [
                                    '<div class="liftnet-Maintenance-TaskRecList" style="height:{height}">',
                                    '<!--     140px -->',
                                    '    <div class="liftnet-Maintenance-TaskRecList-left" style="left:14px" >',
                                    '        <div class="liftnet-font-size14 {titleColor}">{prodno}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{contracted}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{liftno}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{startdate} ~ {enddate}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{liftbrand}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{remark}&nbsp;</div>',
                                    '    </div>',
                                    '    <div class="liftnet-Maintenance-TaskRecList-right" style="padding-top:0px;right:14px">',
                                    '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray liftnet-font-right">{amt}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">{fsd}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-{outdanColor}">{outdan}&nbsp;</div>',
                                    '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">{dannum}次</div>',
                                    '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">{liftstyle}&nbsp;</div>',
                                    '    </div>',
                                    '</div>'
                                ],
                                store: 'eng_insurecontracttabelevator'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});