/*
 * File: app/view/Engineer/EngMonitorProjectElevatorList.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Engineer.EngMonitorProjectElevatorList', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.form.Panel',
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        id: 'EngMonitorProjectElevatorList',
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                id: 'EngMonitorProjectElevatorList_Toolbar',
                title: '电梯列表',
                items: [
                    {
                        xtype: 'button',
                        id: 'EngMonitorProjectElevatorList_BtnReturn',
                        iconCls: 'fa fa-chevron-left'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                layout: 'vbox',
                items: [
                    {
                        xtype: 'formpanel',
                        cls: 'liftnet-search-form',
                        items: [
                            {
                                xtype: 'searchfield',
                                cls: 'liftnet-font-size12',
                                id: 'EngMonitorProjectElevatorList_Search',
                                itemId: 'EngMonitorProjectElevatorList_Search',
                                placeHolder: '注册码、项目地址'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        flex: 1,
                        cls: 'liftnet-monitor-elevatorDetail-listBox',
                        id: 'EngMonitorProjectElevatorList_ListElevator',
                        disableSelection: true,
                        itemTpl: [
                            '<div class="liftnet-monitor-elevatorDetail-listConBox">',
                            '	<div class="liftnet-monitor-listConBox-top">',
                            '    	<div class="liftnet-font-size16 liftnet-fontColor-darkGray liftnet-monitor-listConBox-top-left">{prono}</div>',
                            '    	<div class="liftnet-monitor-listConBox-state liftnet-font-right liftnet-font-size12 {statusColor}">{r3} </div>',
                            '    </div>',
                            '    <div class="liftnet-fontColor-gray liftnet-font-size12">{eleuseaddress}</div>',
                            '<!--     <div class="liftnet-fontColor-gray liftnet-font-size12">{addr}</div>',
                            '    <div class="liftnet-fontColor-gray liftnet-font-size12">最近维保时间：{lastfinishtime}</div> -->',
                            '</div>'
                        ],
                        pressedCls: ' ',
                        store: 'ss_elevatorlist'
                    }
                ]
            }
        ]
    }

});