/*
 * File: app/view/Engineer/EngMaintainPlan.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Engineer.EngMaintainPlan', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.form.Panel',
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                title: '保养计划及实绩',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'EngMaintain_ReturnButton',
                        iconCls: 'fa fa-chevron-left'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        cls: 'liftnet-font-size12',
                        html: '<span style="color:white;">更多...</span>.',
                        id: 'EngMaintain_MorePButton'
                    }
                ]
            },
            {
                xtype: 'container',
                flex: 1,
                id: 'EngMaintainS',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'formpanel',
                        cls: 'liftnet-search-form',
                        height: 52,
                        id: 'EngMaintainPlanS_SearchForm',
                        scrollable: false,
                        items: [
                            {
                                xtype: 'searchfield',
                                cls: 'liftnet-font-size12',
                                id: 'EngMaintainPlanS_FldSearch',
                                itemId: 'EngMaintainPlanS_FldSearch',
                                placeHolder: '项目名称、注册代码、保养类型、保养员'
                            },
                            {
                                xtype: 'button',
                                cls: [
                                    'liftnet-font-size12',
                                    'liftnet-no-border',
                                    'liftnet-fontColor-darkGray'
                                ],
                                docked: 'right',
                                id: 'EngMaintain_BtnTaskStatus',
                                margin: '16 0',
                                width: 70,
                                iconAlign: 'right',
                                iconCls: 'fa fa-angle-down',
                                text: '全部'
                            }
                        ]
                    },
                    {
                        xtype: 'list',
                        flex: 1,
                        cls: 'liftnet-fault-listBox',
                        id: 'EngMaintain_ListPlan',
                        itemTpl: [
                            '<div class="liftnet-Maintenance-TaskRecList">',
                            '    <div class="liftnet-Maintenance-TaskRecList-left">',
                            '        <div class="liftnet-font-size16 {titleColor}">{projectname}</div>',
                            '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{prodno}</div>',
                            '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{plandate}</div>',
                            '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">保养次第：{ordernum}</div>',
                            '    </div>',
                            '    <div class="liftnet-Maintenance-TaskRecList-right" style="padding-top:0px;">',
                            '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray liftnet-font-right">{plantype}</div>',
                            '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">{liftno}</div>',
                            '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">{man}</div>',
                            '        <div class="liftnet-font-size12 liftnet-font-right {stateColor}">{flowstatus} <i class="fa fa-circle-o"></i></div>',
                            '    </div>',
                            '</div>'
                        ],
                        store: 'by_maintainplanlist'
                    }
                ]
            }
        ]
    }

});