/*
 * File: app/view/Engineer/EngReformcheckTask.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Engineer.EngReformcheckTask', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.field.DatePicker',
        'Ext.picker.Date',
        'Ext.field.TextArea',
        'Ext.field.Hidden',
        'Ext.field.Toggle',
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Label',
        'Ext.Img',
        'Ext.ActionSheet',
        'Ext.Spacer'
    ],

    config: {
        itemId: 'EngReformcheckTask',
        layout: 'vbox',
        items: [
            {
                xtype: 'container',
                flex: 1,
                id: 'EngReformcheckTask',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: 'liftnet-toolbar-other',
                        docked: 'top',
                        title: '整改任务',
                        items: [
                            {
                                xtype: 'button',
                                itemId: 'EngReformcheckTask_ReturnButton',
                                iconCls: 'fa fa-chevron-left'
                            }
                        ]
                    },
                    {
                        xtype: 'tabpanel',
                        flex: 1,
                        cls: 'liftnet-tabbar-two',
                        id: 'EngReformcheckTask_TplList',
                        items: [
                            {
                                xtype: 'container',
                                title: '电梯信息',
                                cls: 'liftnet-fault-listBox',
                                itemId: 'EngReformcheckTask_CtnLiftInfo',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'formpanel',
                                        flex: 1,
                                        cls: [
                                            'liftnet-form-info',
                                            'liftnet-font-size14',
                                            'liftnet-lineHeight34'
                                        ],
                                        id: 'EngReformcheckTask_Form',
                                        itemId: 'EngReformcheckTask_Form',
                                        scrollable: 'vertical',
                                        items: [
                                            {
                                                xtype: 'textfield',
                                                label: '客户名称',
                                                name: 'custname',
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '项目名称',
                                                name: 'projectname',
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '项目地址',
                                                name: 'projectaddress',
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '设备注册码',
                                                labelWidth: '40%',
                                                name: 'prono',
                                                required: true
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '使用登记证号',
                                                labelWidth: '40%',
                                                name: 'equno'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '出厂编号',
                                                labelWidth: '40%',
                                                name: 'elevatorno'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '施工许可证',
                                                labelWidth: '40%',
                                                name: 'allowno'
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                id: 'EngReformcheckTask_leafacdate',
                                                itemId: 'EngReformcheckTask_leafacdate',
                                                label: '制造日期',
                                                name: 'leafacdate',
                                                dateFormat: 'Y-m-d',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    yearTo: 2200,
                                                    doneButton: '确认',
                                                    cancelButton: '取消'
                                                }
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                label: '竣工日期',
                                                name: 'finishdate',
                                                dateFormat: 'Y-m-d',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    yearTo: 2200,
                                                    doneButton: '确认',
                                                    cancelButton: '取消'
                                                }
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                label: '首次使用电梯日期',
                                                labelWidth: '50%',
                                                name: 'firstuseliftdate',
                                                dateFormat: 'Y-m-d',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    yearTo: 2200,
                                                    doneButton: '确认',
                                                    cancelButton: '取消'
                                                }
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '梯号',
                                                labelWidth: '40%',
                                                name: 'r3'
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                label: '电梯年检日期',
                                                labelWidth: '50%',
                                                name: 'r7',
                                                dateFormat: 'Y-m-d',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    yearTo: 2200,
                                                    doneButton: '确认',
                                                    cancelButton: '取消'
                                                }
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                label: '下一次年检日期',
                                                labelWidth: '50%',
                                                name: 'r8',
                                                dateFormat: 'Y-m-d',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    yearTo: 2200,
                                                    doneButton: '确认',
                                                    cancelButton: '取消'
                                                }
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                label: '限速器年检日期',
                                                labelWidth: '50%',
                                                name: 'speedcheckdate',
                                                dateFormat: 'Y-m-d',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    yearTo: 2200,
                                                    doneButton: '确认',
                                                    cancelButton: '取消'
                                                }
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                label: '限速器下一次年检日期',
                                                labelWidth: '58%',
                                                name: 'speednextcheckdate',
                                                dateFormat: 'Y-m-d',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    yearTo: 2200,
                                                    doneButton: '确认',
                                                    cancelButton: '取消'
                                                }
                                            },
                                            {
                                                xtype: 'textareafield',
                                                label: '电梯位置描述',
                                                labelWidth: '40%',
                                                name: 'liftloaction'
                                            },
                                            {
                                                xtype: 'selectfield',
                                                cls: 'x-field-picker',
                                                id: 'EngReformcheckTask_typeid',
                                                itemId: 'EngReformcheckTask_typeid',
                                                label: '电梯分类',
                                                labelWidth: '40%',
                                                name: 'typeid',
                                                required: true,
                                                displayField: 'typename',
                                                store: 'eng_lifttypelist',
                                                valueField: 'typeid'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'EngReformcheckTask_elevatorname',
                                                itemId: 'EngReformcheckTask_elevatorname',
                                                label: '电梯型号',
                                                labelWidth: '40%',
                                                name: 'elevatorname',
                                                required: true,
                                                listeners: [
                                                    {
                                                        fn: function(component, eOpts) {
                                                            var me = this;
                                                            me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                        },
                                                        event: 'initialize'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'EngReformcheckTask_facname',
                                                itemId: 'EngReformcheckTask_facname',
                                                label: '电梯品牌',
                                                labelWidth: '40%',
                                                name: 'facname',
                                                required: true,
                                                listeners: [
                                                    {
                                                        fn: function(component, eOpts) {
                                                            var me = this;
                                                            me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                        },
                                                        event: 'initialize'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '电梯制造商',
                                                labelWidth: '40%',
                                                name: 'makeunit'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '载重(kg)',
                                                labelWidth: '40%',
                                                name: 'zzl'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '速度(m/s)',
                                                labelWidth: '40%',
                                                name: 'speed'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '扶梯倾斜角',
                                                labelWidth: '40%',
                                                name: 'fwlc'
                                            },
                                            {
                                                xtype: 'selectfield',
                                                cls: 'x-field-picker',
                                                label: '开门方式',
                                                labelWidth: '40%',
                                                name: 'kmfs',
                                                displayField: 'dswingname',
                                                store: 'eng_kmfslist',
                                                valueField: 'dswingid'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '开门形式备注',
                                                labelWidth: '40%',
                                                name: 'openremark'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '年检到期预警天数',
                                                labelWidth: '50%',
                                                name: 'r9'
                                            },
                                            {
                                                xtype: 'selectfield',
                                                cls: 'x-field-picker',
                                                id: 'EngReformcheckTask_contype',
                                                itemId: 'EngReformcheckTask_contype',
                                                label: '控制方式',
                                                labelWidth: '40%',
                                                name: 'contype',
                                                required: true,
                                                displayField: 'controlname',
                                                store: 'eng_kzfslist',
                                                valueField: 'controlid'
                                            },
                                            {
                                                xtype: 'textfield',
                                                hidden: true,
                                                id: 'EngReformcheckTask_controlnum',
                                                label: '群控台数',
                                                labelWidth: '50%',
                                                name: 'controlnum'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '层',
                                                labelWidth: '40%',
                                                name: 'floor'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '站',
                                                labelWidth: '40%',
                                                name: 'stage'
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '门',
                                                labelWidth: '40%',
                                                name: 'door'
                                            },
                                            {
                                                xtype: 'selectfield',
                                                cls: 'x-field-picker',
                                                label: '电梯使用场所',
                                                labelWidth: '50%',
                                                name: 'useplace',
                                                required: true,
                                                displayField: 'placename',
                                                store: 'eng_placelist',
                                                valueField: 'placeid'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'EngReformcheckTask_domainname',
                                                itemId: 'EngReformcheckTask_domainname',
                                                label: '区域',
                                                labelWidth: '40%',
                                                name: 'domainname',
                                                listeners: [
                                                    {
                                                        fn: function(component, eOpts) {
                                                            var me = this;
                                                            me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                        },
                                                        event: 'initialize'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                cls: 'x-field-picker',
                                                id: 'EngReformcheckTask_domainid',
                                                itemId: 'EngReformcheckTask_domainid',
                                                name: 'domainid'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'EngReformcheckTask_provinciallevelname',
                                                itemId: 'EngReformcheckTask_provinciallevelname',
                                                label: '省份',
                                                labelWidth: '40%',
                                                name: 'provinciallevelname',
                                                listeners: [
                                                    {
                                                        fn: function(component, eOpts) {
                                                            var me = this;
                                                            me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                        },
                                                        event: 'initialize'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                cls: 'x-field-picker',
                                                id: 'EngReformcheckTask_provinciallevelid',
                                                itemId: 'EngFirstCheckTask_provinciallevelid',
                                                name: 'provinciallevelid'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'EngReformcheckTask_citylevelname',
                                                itemId: 'EngReformcheckTask_citylevelname',
                                                label: '市',
                                                labelWidth: '40%',
                                                name: 'citylevelname',
                                                listeners: [
                                                    {
                                                        fn: function(component, eOpts) {
                                                            var me = this;
                                                            me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                        },
                                                        event: 'initialize'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                cls: 'x-field-picker',
                                                id: 'EngReformcheckTask_citylevelid',
                                                itemId: 'EngReformcheckTask_citylevelid',
                                                name: 'citylevelid'
                                            },
                                            {
                                                xtype: 'textfield',
                                                id: 'EngReformcheckTask_countylevelname',
                                                itemId: 'EngFirstCheckTask_countylevelname',
                                                label: '区',
                                                labelWidth: '40%',
                                                name: 'countylevelname',
                                                listeners: [
                                                    {
                                                        fn: function(component, eOpts) {
                                                            var me = this;
                                                            me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                        },
                                                        event: 'initialize'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                cls: 'x-field-picker',
                                                id: 'EngReformcheckTask_countylevelid',
                                                itemId: 'EngReformcheckTask_countylevelid',
                                                name: 'countylevelid'
                                            },
                                            {
                                                xtype: 'textfield',
                                                cls: 'x-field-search',
                                                id: 'EngReformcheckTask_r2',
                                                itemId: 'EngReformcheckTask_r2',
                                                label: '坐标',
                                                labelWidth: '40%',
                                                name: 'r2',
                                                listeners: [
                                                    {
                                                        fn: function(component, eOpts) {
                                                            var me = this;
                                                            me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                        },
                                                        event: 'initialize'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '计划检验日期',
                                                labelWidth: '40%',
                                                name: 'plandate',
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'datepickerfield',
                                                label: '检验日期',
                                                labelWidth: '50%',
                                                name: 'checkdate',
                                                dateFormat: 'Y-m-d',
                                                picker: {
                                                    slotOrder: [
                                                        'year',
                                                        'month',
                                                        'day'
                                                    ],
                                                    yearTo: 2200,
                                                    doneButton: '确认',
                                                    cancelButton: '取消'
                                                }
                                            },
                                            {
                                                xtype: 'textareafield',
                                                id: 'EngReformcheckTask_checkuserName',
                                                itemId: 'EngReformcheckTask_checkuserName',
                                                label: '检验人员',
                                                labelWidth: '40%',
                                                name: 'checkuserName',
                                                required: true,
                                                listeners: [
                                                    {
                                                        fn: function(component, eOpts) {
                                                            var me = this;
                                                            me.element.on('tap', function(e, t) { me.fireEvent('tap', me, e, t); }, me);
                                                        },
                                                        event: 'initialize'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'textfield',
                                                label: '报告编号',
                                                labelWidth: '40%',
                                                name: 'reportid',
                                                required: true,
                                                readOnly: true
                                            },
                                            {
                                                xtype: 'togglefield',
                                                id: 'EngReformcheckTask_isreformflag',
                                                label: '是否需要整改',
                                                labelWidth: '40%',
                                                name: 'isreformflag',
                                                maxValueCls: 'x-toggle-on-red',
                                                minValueCls: 'x-toggle-off-green'
                                            },
                                            {
                                                xtype: 'textareafield',
                                                hidden: true,
                                                label: '备注'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                name: 'creator'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                name: 'projectid'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                name: 'custid'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                name: 'createname'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                name: 'createdeptname'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                name: 'liftautono'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                name: 'kjkd'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                id: 'EngReformcheckTask_checkuser',
                                                itemId: 'EngReformcheckTask_checkuser',
                                                name: 'checkuser'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                name: 'createdeptid'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                name: 'elevatorid'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                id: 'EngReformcheckTask_jnlno',
                                                itemId: 'EngReformcheckTask_jnlno',
                                                name: 'jnlno'
                                            },
                                            {
                                                xtype: 'hiddenfield',
                                                id: 'EngReformcheckTask_r1',
                                                itemId: 'EngFirstCheckTask_r1',
                                                name: 'r1'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'liftnet-button-three',
                                            'liftnet-button'
                                        ],
                                        id: 'EngReformcheck_Panel1',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                id: 'EngReformcheckTask_BtnSave',
                                                itemId: 'EngReformcheckTask_BtnSave',
                                                text: '保存'
                                            },
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                cls: 'liftnet-buttonColor-red',
                                                id: 'EngReformcheckTask_BtnCommit',
                                                itemId: 'EngReformcheckTask_BtnCommit',
                                                text: '提交'
                                            },
                                            {
                                                xtype: 'button',
                                                flex: 1,
                                                cls: 'liftnet-buttonColor-green',
                                                id: 'EngReformcheckTask_BtnCancel',
                                                itemId: 'EngReformcheckTask_BtnCancel'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'liftnet-button-two',
                                            'liftnet-button'
                                        ],
                                        hidden: true,
                                        id: 'EngReformcheck_Panel2',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'button',
                                                cls: 'liftnet-buttonColor-green',
                                                docked: 'left',
                                                id: 'EngReformcheckTask_BtnAgree',
                                                itemId: 'EngReformcheckTask_BtnAgree',
                                                text: '同意'
                                            },
                                            {
                                                xtype: 'button',
                                                cls: 'liftnet-buttonColor-red',
                                                docked: 'right',
                                                id: 'EngReformcheckkTask_BtnDisagree',
                                                itemId: 'EngReformcheckTask_BtnDisagree',
                                                text: '不同意'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                title: '检验项目',
                                itemId: 'EngReformcheckTask_CtnCheckProject',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'list',
                                        flex: 1,
                                        cls: 'liftnet-home-listBox',
                                        id: 'EngReformcheckTask_CheckProList',
                                        itemId: 'EngReformcheckTask_CheckProList',
                                        disableSelection: true,
                                        itemTpl: [
                                            '<div style="width:100%;height:72px;" class="liftnet-font-size12 liftnet-fontColor-darkGray">',
                                            '    <div style="float:left;width:85%">',
                                            '        <div style="width:100%;" >',
                                            '            <div style="width:20%;float:left;text-align:center;line-height:24px;">{jnum}&nbsp;</div>',
                                            '            <div style="width:20%;float:left;text-align:center;line-height:24px;">{projecttype}&nbsp;</div>',
                                            '            <div style="width:60%;float:left;text-align:center;line-height:24px;overflow:hidden; text-overflow:ellipsis;white-space: nowrap;">{ctype}&nbsp;</div>',
                                            '        </div>',
                                            '        <div style="overflow:hidden; text-overflow:ellipsis;white-space: nowrap;width:100%;padding-left:22px;line-height:24px;">{projectcontent}&nbsp;</div>',
                                            '        <div style="overflow:hidden; text-overflow:ellipsis;white-space: nowrap;width:100%;padding-left:22px;line-height:24px;">{checkresult}&nbsp;</div>',
                                            '    </div>',
                                            '    ',
                                            '    <div style="float:right;width:15%;">',
                                            '        <div id = \'clickArea\' style="width:100%;float:right;text-align:center;line-height:72px;">',
                                            '            <tpl if=\'checkverdict == "√"\'>',
                                            '            <!--定义一个id(statusArea)用于识别点击位置',
                                            '                在list的itemtap事件中，用e.target.id可获得被点击对象的id-->',
                                            '                <i id=\'statusArea\' class=\'fa fa-lg fa-check-circle\' style=\'color:green\'></i>',
                                            '            <tpl else>',
                                            '            <!--如果状态为N，显示“红色叉” -->',
                                            '            <tpl if=\'checkverdict == "×"\'>',
                                            '                <i id=\'statusArea\' class=\'fa fa-lg fa-times-circle\' style=\'color:red\'></i>',
                                            '            <tpl else>',
                                            '                <!--默认状态为空，显示“灰色横” -->',
                                            '                <i id=\'statusArea\' class=\'fa fa-lg fa-minus-circle\' style=\'color:#ccc\'></i>',
                                            '            </tpl>',
                                            '        </tpl>',
                                            '       </div>',
                                            '   </div>',
                                            '</div>	'
                                        ],
                                        store: 'firstcheck_task_checkproject'
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: 'liftnet-button',
                                        height: 30,
                                        id: 'EngReformcheck_Panel3',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'label',
                                                centered: true,
                                                cls: [
                                                    'liftnet-fontColor-black',
                                                    'liftnet-font-size16'
                                                ],
                                                html: '',
                                                id: 'EngReformcheck_LblCount',
                                                itemId: 'EngReformcheck_LblCount'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'liftnet-button-two',
                                            'liftnet-button'
                                        ],
                                        hidden: true,
                                        id: 'EngReformcheck_Panel4',
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'button',
                                                docked: 'left',
                                                id: 'EngFirstCheckTask_BtnSave3',
                                                itemId: 'EngReformcheckTask_BtnSave',
                                                text: '保存'
                                            },
                                            {
                                                xtype: 'button',
                                                cls: 'liftnet-buttonColor-green',
                                                docked: 'right',
                                                id: 'EngFirstCheckTask_BtnCommit3',
                                                itemId: 'EngReformcheckTask_BtnCommit',
                                                text: '提交'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                title: '现场信息',
                                itemId: 'EngFirstCheckTask_CtnSceneInfo',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        height: 333,
                                        id: 'EngFirstCheckTask_ImgCtn1',
                                        itemId: 'EngFirstCheckTask_ImgCtn',
                                        padding: '20 0',
                                        layout: 'vbox',
                                        items: [
                                            {
                                                xtype: 'panel',
                                                flex: 1,
                                                margin: '',
                                                style: 'margin-top:5px;',
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        flex: 1,
                                                        layout: 'vbox',
                                                        items: [
                                                            {
                                                                xtype: 'image',
                                                                cls: 'liftnet-fault-trackTop-img',
                                                                height: '60%',
                                                                id: 'EngFirstCheckTask_photo_7',
                                                                itemId: 'EngFirstCheckTask_camera',
                                                                width: '100%',
                                                                src: 'resources/images/camera.png'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                html: '',
                                                                id: 'EngFirstCheckTask_photo_1_label_11',
                                                                margin: '0 15 0 0',
                                                                padding: '0 0 0 15',
                                                                style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_1_label_21',
                                                                padding: '0 0 0 15'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        flex: 1,
                                                        items: [
                                                            {
                                                                xtype: 'image',
                                                                cls: 'liftnet-fault-trackTop-img',
                                                                height: '60%',
                                                                id: 'EngFirstCheckTask_photo_8',
                                                                width: '100%',
                                                                src: 'resources/images/notPhoto.png'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_2_label_11',
                                                                margin: '0 15 0 0',
                                                                padding: '0 0 0 15',
                                                                style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_2_label_21',
                                                                padding: '0 0 0 15'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        flex: 1,
                                                        items: [
                                                            {
                                                                xtype: 'image',
                                                                cls: 'liftnet-fault-trackTop-img',
                                                                height: '60%',
                                                                id: 'EngFirstCheckTask_photo_9',
                                                                width: '100%',
                                                                src: 'resources/images/notPhoto.png'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_3_label_11',
                                                                margin: '0 15 0 0',
                                                                padding: '0 0 0 15',
                                                                style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_3_label_21',
                                                                padding: '0 0 0 15'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'panel',
                                                flex: 1,
                                                margin: '20 0',
                                                style: 'margin-top:5px;',
                                                layout: 'hbox',
                                                items: [
                                                    {
                                                        xtype: 'container',
                                                        flex: 1,
                                                        items: [
                                                            {
                                                                xtype: 'image',
                                                                cls: 'liftnet-fault-trackTop-img',
                                                                height: '60%',
                                                                id: 'EngFirstCheckTask_photo_10',
                                                                width: '100%',
                                                                src: 'resources/images/notPhoto.png'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_4_label_11',
                                                                margin: '0 15 0 0',
                                                                padding: '0 0 0 15',
                                                                style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_4_label_21',
                                                                padding: '0 0 0 15'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        flex: 1,
                                                        items: [
                                                            {
                                                                xtype: 'image',
                                                                cls: 'liftnet-fault-trackTop-img',
                                                                height: '60%',
                                                                id: 'EngFirstCheckTask_photo_11',
                                                                width: '100%',
                                                                src: 'resources/images/notPhoto.png'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_5_label_11',
                                                                margin: '0 15 0 0',
                                                                padding: '0 0 0 15',
                                                                style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_5_label_21',
                                                                padding: '0 0 0 15'
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'container',
                                                        flex: 1,
                                                        items: [
                                                            {
                                                                xtype: 'image',
                                                                cls: 'liftnet-fault-trackTop-img',
                                                                height: '60%',
                                                                id: 'EngFirstCheckTask_photo_12',
                                                                width: '100%',
                                                                src: 'resources/images/notPhoto.png'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_6_label_11',
                                                                margin: '0 15 0 0',
                                                                padding: '0 0 0 15',
                                                                style: 'white-space:nowrap; overflow:hidden; text-overflow:ellipsis;'
                                                            },
                                                            {
                                                                xtype: 'label',
                                                                hidden: false,
                                                                id: 'EngFirstCheckTask_photo_6_label_21',
                                                                padding: '0 0 0 15'
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'label',
                                        centered: true,
                                        docked: 'top',
                                        hidden: true,
                                        html: '<div style="text-align:center;margin:20px">没有相关现场信息</div>',
                                        id: 'EngFirstCheckTask_NoSceneInfo1',
                                        itemId: 'EngFirstCheckTask_NoSceneInfo',
                                        width: '100%'
                                    },
                                    {
                                        xtype: 'actionsheet',
                                        height: 65,
                                        hidden: true,
                                        id: 'task_camera_show1',
                                        itemId: 'Task_camera_show',
                                        hideOnMaskTap: true,
                                        layout: 'hbox',
                                        items: [
                                            {
                                                xtype: 'button',
                                                id: 'task_source_camear1',
                                                itemId: 'task_source_camear',
                                                width: 110,
                                                text: '相机'
                                            },
                                            {
                                                xtype: 'spacer'
                                            },
                                            {
                                                xtype: 'button',
                                                id: 'task_source_album1',
                                                itemId: 'task_source_album',
                                                width: 110,
                                                text: '相册'
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                title: '零部件信息',
                                itemId: 'EngFirstCheckTask_CtnPartInfo',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'list',
                                        flex: 1,
                                        cls: 'liftnet-fault-listBox',
                                        id: 'EngFirstCheckTask_PartList1',
                                        disableSelection: true,
                                        itemTpl: [
                                            '<!-- <div class = "liftnet-font-size14 liftnet-fontColor-gray">',
                                            '    <div>编码:</div>',
                                            '    <div>零件名称:</div>',
                                            '    <div>型号:</div>',
                                            '    <div>序列号:</div>',
                                            '    <div>零件类型:</div>',
                                            '</div> -->',
                                            '',
                                            '<div class="liftnet-Maintenance-TaskRecList" style="height:100px">',
                                            '    <div class="liftnet-Maintenance-TaskRecList-left" style="left:14px" >',
                                            '        <div class="liftnet-font-size16 {titleColor}">{partsid}&nbsp;</div>',
                                            '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{partsname}&nbsp;</div>',
                                            '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{partsmodel}&nbsp;</div>',
                                            '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray">{partsno}&nbsp;</div>',
                                            '    </div>',
                                            '    <div class="liftnet-Maintenance-TaskRecList-right" style="padding-top:0px;right:14px">',
                                            '        <div class="liftnet-font-size12 liftnet-fontColor-darkGray liftnet-font-right">{partstypeid}&nbsp;</div>',
                                            '        <div class="liftnet-font-size12 liftnet-font-right {textcolor}">{iscoreShow}&nbsp;</div>',
                                            '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">{partsremark}&nbsp;</div>',
                                            '        <div class="liftnet-font-size12 liftnet-font-right liftnet-fontColor-darkGray">数量:{num}&nbsp;</div>',
                                            '    </div>',
                                            '</div>'
                                        ],
                                        store: 'eng_firstcheckparts'
                                    },
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'liftnet-button',
                                            'liftnet-button-one'
                                        ],
                                        id: 'EngFirstCheckTask_PanelAdd1',
                                        itemId: 'EngFirstCheckTask_PanelAdd',
                                        items: [
                                            {
                                                xtype: 'button',
                                                cls: [
                                                    'liftnet-no-border',
                                                    'x-buttonColor-white'
                                                ],
                                                id: 'EngFirstCheckTask_BtnAddParts1',
                                                text: '<i class=\'fa fa-plus\'></i>&nbsp;&nbsp;增加'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'label',
                                        centered: true,
                                        docked: 'top',
                                        hidden: true,
                                        html: '<div style="text-align:center;margin:20px">没有相关零部件信息</div>',
                                        id: 'EngFirstCheckTask_NoPartInfo1',
                                        itemId: 'EngFirstCheckTask_NoPartInfo',
                                        width: '100%'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }

});