/*
 * File: app/view/Admin/NoUse/AdmAudSwspdetailList.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Admin.NoUse.AdmAudSwspdetailList', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        id: 'AdmAudSwspdetailList',
        layout: 'vbox',
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                title: '商务审批列表',
                items: [
                    {
                        xtype: 'button',
                        id: 'AdmAudSwspdetailList_ButReturn',
                        iconCls: 'fa fa-chevron-left'
                    }
                ]
            },
            {
                xtype: 'list',
                flex: 1,
                cls: 'liftnet-aApprove-listBox',
                id: 'AdmAudSwspdetailList_ListDetailed',
                disableSelection: true,
                itemTpl: [
                    '<div class="liftnet-aApprove-listConBox">',
                    '	<div class="liftnet-aApprove-listConBox-top liftnet-font-size16 liftnet-fontColor-darkGray">申请项目:{citemid}</div>',
                    '    <div class="liftnet-fontColor-gray liftnet-font-size12">原因说明：{causerec}</div>',
                    '    <div class="liftnet-fontColor-gray liftnet-font-size12">原因分析：{causeanalyse}</div>',
                    '</div>'
                ],
                pressedCls: ' ',
                store: 'NoUsed.aud_swspdetail_detailed'
            }
        ]
    }

});