/*
 * File: app/store/NoUsed/aud_byzydetail_detailed.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.NoUsed.aud_byzydetail_detailed', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'NoUsed.aud_byzydetail_detailed',
        fields: [
            {
                name: 'pordid',
                type: 'string'
            },
            {
                name: 'elevatorid',
                type: 'string'
            },
            {
                name: 'fsd',
                type: 'string'
            },
            {
                name: 'high',
                type: 'string'
            },
            {
                name: 'mugstartdate',
                type: 'string'
            },
            {
                name: 'mugenddate',
                type: 'string'
            },
            {
                name: 'price',
                type: 'string'
            },
            {
                name: 'r18',
                type: 'string'
            },
            {
                name: 'yearcheckprice',
                type: 'string'
            },
            {
                name: 'sumcount',
                type: 'string'
            },
            {
                name: 'detailrem',
                type: 'string'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;

        if(global.isWorklight()) {
            // adapter取数
            var url = '/aud/api/1.0/byzyaud/'+'任务号';
            var userid = global.getUserId();
            var adapterParm = {userid:'用户ID',billno:'流水号'};

            callPostAdapter(
                url, adapterParm,
                function(ret) {
                    me.setData(ret.data);
                    onSuccess();
                },
            onFailure);
        } else {
            // 保养作业查看-明细信息-演示数据
            this.setData([
            {
                pordid: '注册码',
                elevatorid: '型号',
                fsd: '层/站/门',
                high: '提升高度',
                mugstartdate: '保养开始日期',
                mugenddate: '保养结束日期',
                price: '单价',
                r18: '保养月数',
                yearcheckprice: '年检费',
                sumcount: '金额',
                detailrem: '备注'
            }
            ]);

            onSuccess();
        }
    },

    updateDat: function(onSuccess, onFailure, parm) {

    },

    filteDat: function(parm) {

    }

});