/*
 * File: app/store/NoUsed/ss_guserdetaillist.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.NoUsed.ss_guserdetaillist', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'NoUsed.ss_guserdetaillist',
        fields: [
            {
                name: 'userid',
                type: 'string'
            },
            {
                name: 'phone',
                type: 'string'
            },
            {
                name: 'status',
                type: 'string'
            },
            {
                name: 'status',
                type: 'string'
            },
            {
                name: 'statusing',
                type: 'string'
            },
            {
                name: 'addr',
                type: 'string'
            },
            {
                name: 'lasttime',
                type: 'string'
            },
            {
                name: 'stauts',
                type: 'string'
            },
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'laststatustime',
                type: 'string'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        if(global.isWorklight()) {// adapter取数

        } else {
            // 人员信息-演示数据
            // 接口无提供字段：statusing
            this.setData([
            {
                userid: '陈晓明',
                phone: '13888888888',
                status: '路途中',
                statusing: 'resources/images/trackListBox-icon02.png',
                addr: '广州市凯旋大酒店有限公司凯旋华美达大酒店',
                lasttime: '2015-11-18 17:20',
                title: '路途中 保养任务SDASF345',
                laststatustime: '2015-11-18 17:20'
            },
            {
                userid: '陈晓明',
                phone: '13888888888',
                status: '路途中',
                statusing: 'resources/images/trackListBox-icon01.png',
                addr: '广州市凯旋大酒店有限公司凯旋华美达大酒店',
                lasttime: '2015-11-18 17:20',
                title: '完成 保养任务SDASF345',
                laststatustime: '2015-11-18 17:20'
            }
            ]);

                onSuccess();
            }
    },

    updateDat: function(onSuccess, onFailure, parm) {

    },

    filteDat: function(parm) {

    }

});