/*
 * File: app/store/NoUsed/sx_cominfolist.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.NoUsed.sx_cominfolist', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'NoUsed.sx_cominfolist',
        fields: [
            {
                name: 'shortunitname',
                type: 'string'
            },
            {
                name: 'unitname',
                type: 'string'
            },
            {
                name: 'serviceno',
                type: 'string'
            },
            {
                name: 'elevatorno',
                type: 'string'
            },
            {
                name: 'addr',
                type: 'string'
            },
            {
                name: 'floorstationdoor',
                type: 'string'
            },
            {
                name: 'storageid',
                type: 'string'
            },
            {
                name: 'storagename',
                type: 'string'
            },
            {
                name: 'specno',
                type: 'string'
            },
            {
                name: 'elevatorid',
                type: 'string'
            },
            {
                name: 'dtid',
                type: 'string'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;

        if(global.isWorklight()) {
            // adapter取数
            var url = '/sx/api/1.0/cominfolist';
            var userid = global.getUserId();
            var adapterParm = {userid: '用户ID', shortunitname: '报修单位简称', serviceNo: '电梯服务号', addr: '故障地址', pageno: '从第几条开始, 第一条是0', pagelen: '取几条数据'};

            callPostAdapter(
                url, adapterParm,
                function(ret) {
                    me.setData(ret.data);
                    onSuccess();
                },
            onFailure);
        } else {
            // 24.点击“报价单位”，获取报价单位及设备码列表，选择后自动填写该设备相关信息到表单
            this.setData();

                onSuccess();
            }
    },

    updateDat: function(onSuccess, onFailure, parm) {

    },

    filteDat: function(parm) {

    }

});