/*
 * File: app/store/NoUsed/sx_ssxdetail.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.NoUsed.sx_ssxdetail', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'NoUsed.sx_ssxdetail',
        fields: [
            {
                name: 'reportor',
                type: 'string'
            },
            {
                name: 'reportortel',
                type: 'string'
            },
            {
                name: 'reportordate',
                type: 'string'
            },
            {
                name: 'unitname',
                type: 'string'
            },
            {
                name: 'istrap',
                type: 'string'
            },
            {
                name: 'serviceno',
                type: 'string'
            },
            {
                name: 'elevatorno',
                type: 'string'
            },
            {
                name: 'addr',
                type: 'string'
            },
            {
                name: 'floor',
                type: 'string'
            },
            {
                name: 'station',
                type: 'string'
            },
            {
                name: 'storageid',
                type: 'string'
            },
            {
                name: 'elevatorid',
                type: 'string'
            },
            {
                name: 'calloutfaulttypeid',
                type: 'string'
            },
            {
                name: 'calloutcontent',
                type: 'string'
            },
            {
                name: 'expectarrivetime',
                type: 'string'
            },
            {
                name: 'remark',
                type: 'string'
            },
            {
                name: 'createtime',
                type: 'string'
            },
            {
                name: 'trno',
                type: 'string'
            },
            {
                name: 'specno',
                type: 'string'
            },
            {
                name: 'isapprove',
                type: 'string'
            },
            {
                name: 'dutyusername',
                type: 'string'
            },
            {
                name: 'dutyuserid',
                type: 'string'
            },
            {
                name: 'linkphone',
                type: 'string'
            },
            {
                name: 'sxly',
                type: 'string'
            },
            {
                name: 'facename',
                type: 'string'
            }
        ]
    },

    updateDat: function(onSuccess, onFailure, parm) {
        var me = this;
        var url = '/adapters/sx/api/1.0/sxdetail';
        var userid = global.getUserId();
        console.log(parm);

        if(global.isWorklight()) {
            callPostAdapter(
                url, parm,
                function(ret) {
                    onSuccess(ret.trNo);
                },
                onFailure);
        } else {
            onSuccess('BXDEMO-12345678');
        }
    }

});