/*
 * File: app/view/Common/ComHomeInformation.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Common.ComHomeInformation', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Img',
        'Ext.form.Panel',
        'Ext.Label',
        'Ext.field.Password'
    ],

    config: {
        cls: 'liftnet-myInformation',
        id: 'ComHomeInformation',
        layout: 'vbox',
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                title: '我的资料',
                items: [
                    {
                        xtype: 'button',
                        id: 'ComHomeInformation_BtnReturn',
                        iconCls: 'fa fa-chevron-left'
                    }
                ]
            },
            {
                xtype: 'panel',
                flex: 1,
                layout: 'vbox',
                scrollable: true,
                items: [
                    {
                        xtype: 'panel',
                        cls: [
                            'liftnet-myInformation-head',
                            'liftnet-border-radius50'
                        ],
                        height: 90,
                        width: 90,
                        zIndex: 10,
                        items: [
                            {
                                xtype: 'button',
                                cls: [
                                    'liftnet-no-border',
                                    'liftnet-border-radius50',
                                    'liftnet-bgColor-red',
                                    'liftnet-fontColor-white',
                                    'liftnet-myInformation-photograph'
                                ],
                                hidden: false,
                                html: '<i class="fa fa-camera-retro"></i>',
                                id: 'ComHomeInformation_BtnPrint',
                                itemId: 'mybutton20'
                            },
                            {
                                xtype: 'image',
                                cls: 'liftnet-border-radius50',
                                height: 80,
                                id: 'ComHomeInformation_ImgAvatar',
                                margin: 5,
                                width: 80,
                                src: 'resources/images/home_icon.png'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'liftnet-myInformation-top',
                        height: 100,
                        id: 'MyAvatarBg',
                        margin: ''
                    },
                    {
                        xtype: 'panel',
                        cls: 'liftnet-bgColor-white',
                        height: 60
                    },
                    {
                        xtype: 'formpanel',
                        height: 240,
                        id: 'form_setting_userinfo',
                        margin: '0 10',
                        scrollable: false,
                        items: [
                            {
                                xtype: 'panel',
                                cls: [
                                    'liftnet-bgColor-white',
                                    'liftnet-myInformation-inputBox'
                                ],
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: 'liftnet-font-center',
                                        html: '输入旧密码'
                                    },
                                    {
                                        xtype: 'passwordfield',
                                        cls: 'liftnet-fontColor-green',
                                        id: 'ComHomeInformation_FldOldPassword',
                                        clearIcon: false,
                                        label: '<i class="fa fa-unlock-alt liftnet-fontColor-gray"></i>',
                                        labelAlign: 'right',
                                        labelWidth: 44,
                                        name: 'oldpasswd',
                                        placeHolder: '输入旧密码'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: [
                                    'liftnet-bgColor-white',
                                    'liftnet-myInformation-inputBox'
                                ],
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: 'liftnet-font-center',
                                        html: '输入新密码'
                                    },
                                    {
                                        xtype: 'passwordfield',
                                        cls: 'liftnet-fontColor-green',
                                        id: 'ComHomeInformation_FldNewPassword1',
                                        clearIcon: false,
                                        label: '<i class="fa fa-unlock-alt liftnet-fontColor-gray"></i>',
                                        labelAlign: 'right',
                                        labelWidth: 44,
                                        name: 'passwd',
                                        placeHolder: '输入新密码'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: [
                                    'liftnet-bgColor-white',
                                    'liftnet-myInformation-inputBox'
                                ],
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: 'liftnet-font-center',
                                        html: '确认新密码'
                                    },
                                    {
                                        xtype: 'passwordfield',
                                        cls: 'liftnet-fontColor-green',
                                        id: 'ComHomeInformation_FldNewPassword2',
                                        clearIcon: false,
                                        label: '<i class="fa fa-lock liftnet-fontColor-green"></i>',
                                        labelAlign: 'right',
                                        labelWidth: 44,
                                        name: 'checkpasswd',
                                        placeHolder: '确认新密码'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: [
                            'liftnet-button',
                            'liftnet-button-one'
                        ],
                        items: [
                            {
                                xtype: 'button',
                                id: 'ComHomeInformation_BtnChangePassword',
                                text: '确定'
                            }
                        ]
                    }
                ]
            }
        ]
    }

});