/*
 * File: app/store/aud_gcbjdetail.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.aud_gcbjdetail', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'aud_gcbjdetail',
        fields: [
            {
                name: 'taskid',
                type: 'string'
            },
            {
                name: 'billno',
                type: 'string'
            },
            {
                name: 'custid',
                type: 'string'
            },
            {
                name: 'projectname',
                type: 'string'
            },
            {
                name: 'quoteaddress',
                type: 'string'
            },
            {
                name: 'busstype',
                type: 'string'
            },
            {
                name: 'r22',
                type: 'string'
            },
            {
                name: 'r13',
                type: 'string'
            },
            {
                name: 'quotedate',
                type: 'string'
            },
            {
                name: 'operationid',
                type: 'string'
            },
            {
                name: 'custspecassu',
                type: 'string'
            },
            {
                name: 'rem',
                type: 'string'
            },
            {
                name: 'r9',
                type: 'string'
            },
            {
                name: 'r10',
                type: 'string'
            },
            {
                name: 'r18',
                type: 'string'
            },
            {
                name: 'allcount',
                type: 'string'
            },
            {
                name: 'r16',
                type: 'string'
            },
            {
                name: 'audrem',
                type: 'string'
            },
            {
                name: 'citemid',
                type: 'string'
            },
            {
                name: 'causerec',
                type: 'string'
            },
            {
                name: 'causeanalyse',
                type: 'string'
            },
            {
                name: 'detaillist',
                type: 'auto'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;

        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/aud/api/1.0/gcbjdetail';
            var userid = global.getUserId();
            var adapterParm = {userid: userid, billno: parm};

            callPostAdapter(
                url, adapterParm,
                function(ret) {
                    me.setData(ret.data);
                    onSuccess();
                },
            onFailure);
        } else {
            // 工程报价联络书查看-演示数据
            this.setData([
                {
                    taskid: 'gcbj999167',
                    billno: 'gcbj',
                    custid: '越秀集团',
                    projectname: '越秀城市广场',
                    quoteaddress: '广州市东风中路200号',
                    r13: '支票或汇款',
                    quotedate: '2014-12-25',
                    operationid: '李晨',
                    custspecassu: '',
                    rem: '合同签定后七天内付清',
                    r9: '2015-01-01',
                    r10: '2015-12-31',
                    r18: '12',
                    allcount: '3',
                    r16: '14400',
                    audrem: '通过',//'审批意见',
                    detaillist: [
                        {
                            elevatorid: 'ABCD12345',//'电梯型号',
                            facinfo: '日立', //'品牌',
                            floor: '16', //'层',
                            stage: '17', //'站',
                            door: '1', //'门',
                            high: '60', //'提升高度',
                            fsdh: '16/17/1/60', //'层/站/门/提升高度',
                            sprice: '500.00', //'保养月单价(元)',
                            r1: '12', //'保养月数',
                            num: '2', //'台数',
                            eletype: '直梯', //'电梯类型',
                            mugstartdate:'2015-10-01', //'开始日期',
                            mugenddate: '2016-09-30', //'结束日期',
                            countprice: '12000.00' //'合计'
                        },
                        {
                            elevatorid: 'ABCD987654321',//'电梯型号',
                            facinfo: '广日', //'品牌',
                            floor: '16', //'层',
                            stage: '17', //'站',
                            door: '1', //'门',
                            high: '60', //'提升高度',
                            fsdh: '16/17/1/60', //'层/站/门/提升高度',
                            sprice: '500.00', //'保养月单价(元)',
                            r1: '12', //'保养月数',
                            num: '1', //'台数',
                            eletype: '直梯', //'电梯类型',
                            mugstartdate:'2015-10-01', //'开始日期',
                            mugenddate: '2016-09-30', //'结束日期',
                            countprice: '6000.00' //'合计'
                        }
                   ]
                }
            ]);

            onSuccess();
        }
    },

    updateDat: function(onSuccess, onFailure, parm) {

    },

    filteDat: function(parm) {

    }

});