/*
 * File: app/store/by_bymissiondetail.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.by_bymissiondetail', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'by_bymissiondetail',
        fields: [
            {
                name: 'ProjectName'
            },
            {
                name: 'ProjectAddress'
            },
            {
                name: 'ContractID'
            },
            {
                name: 'ContractNum'
            },
            {
                name: 'TaskNum'
            },
            {
                name: 'ReadFlag'
            },
            {
                name: 'Remark'
            },
            {
                name: 'taskname'
            },
            {
                name: 'nextstate'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;
        var adapterParm = {
            userid: global.getUserId(),
            rowid: parm
        };
        console.log(adapterParm);
        this.setData([]);
        if(global.isWorklight()) {
            var url = '/adapters/by/api/1.0/bymissiondetail';
            callPostAdapter(
                url, adapterParm,
                function(ret) {
                    me.setData(ret.data);
                    onSuccess(ret.data.length);
                },
                onFailure);
        } else {
            this.setData([
                {
                    ProjectName:			'广州华越友联',			//项目名称
                    ProjectAddress:			'广州市荔湾区黄沙大道某个旮旯某层楼某个房间',	//项目地址
                    ContractID:				'16保110',	//合同编号
                    ContractNum:			'12',			//合同总台数
                    TaskNum:				'3',		//选择台数
                    ReadFlag:				'0',		//合同调阅权限
                    Remark:					'黄沙大道144号',	//备注
                    taskname:				'刘翔(维保一组)',	//保养班组
                    nextstate:				[{name:"提交",url:"http://127.0.0.1/提交"}],

                }
            ]);
            onSuccess(1);
        }
    }

});