/*
 * File: app/store/by_maintainRecption.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.by_maintainRecption', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'by_maintainRecption',
        fields: [
            {
                name: 'projectname'
            },
            {
                name: 'projectaddress'
            },
            {
                name: 'contractid'
            },
            {
                name: 'contractnum'
            },
            {
                name: 'tasknum'
            },
            {
                name: 'readflag'
            },
            {
                name: 'storagename'
            },
            {
                name: 'attention'
            },
            {
                name: 'detail'
            },
            {
                name: 'nextstate'
            },
            {
                name: 'jnlno'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;
        var adapterParm = {
            userid: global.getUserId(),
            jnlno: parm
        };
        this.setData([]);
        if(global.isWorklight()) {
            var url = '/adapters/byrw/api/1.0/byrwrecdetail';
            callPostAdapter(
                url, adapterParm,
                function(ret) {
                    me.setData(me.decDat(ret.data));
                    onSuccess(ret.data.length);
                },
                onFailure);
        } else {
            this.setData([
                {
                 projectname: '第一个项目',
                 projectaddress: '就在那个地方',
                 contractid: '15保123' ,
                 contractnum: '20',
                 tasknum: '15',
                 readflag: 'Y',
                 storagename: '维保一组' ,
                 attention: '注意危险',
                 jnlno:'1212',
                 detail: [
                     {
                         liftno:'A1',
                         prodno:'3110-258963-585479-54786',
                         modelname:'HGP',
                         fsd:'10/10/10'
                     }
                 ],
                    nextstate:[
                        {name:"接收",state:'A'},
                        {name:"退回",state:'B'},
                    ]
                }
            ]);
            onSuccess(1);
        }
    },

    decDat: function(data) {
        if(!data) return([]);

        for(var i=0;i<data.length; i++) {
            switch(data[i].readflag) {
                case 'Y':
                    data[i].readflag = '是';
                    break;

                case 'N':
                    data[i].readflag = '否';
                    break;
            }
        }

        return(data);
    }

});