/*
 * File: app/store/common_getspecno.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.common_getspecno', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'common_getspecno',
        fields: [
            {
                name: 'specno'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;
        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/common/api/1.0/getspecno';
            callPostAdapter(
                url, parm,
                function(ret) {
                    var d = ret.data;
                    var n = d.length;
                    for(var i=0; i<n; i++) {
                        me.add(d[i]);
                    }
                    onSuccess(n);
                },
                onFailure);
        } else {
            var start = parm.pageno, end = parm.pageno + parm.pagelen - 1;
            end = end>1058? 1058:end;

            for(var i=start; i<=end; i++) {
                this.add({
                    specno: '型号' + (i+1),
                });
            }
            // 演示数据
            onSuccess(end - start + 1);
        }
    }

});