/*
 * File: app/store/common_job_choosecheckeduser.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.common_job_choosecheckeduser', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'common_job_choosecheckeduser',
        fields: [
            {
                name: 'userid'
            },
            {
                name: 'username'
            },
            {
                name: 'departmentid'
            },
            {
                name: 'department'
            },
            {
                name: 'usertype'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;

        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/liftnet/common/api/1.0/';
            var userid = global.getUserId();

        //     var adapterParm = {userid: userid};

            callPostAdapter(
                url, parm,
                function(ret) {
                    me.setData(ret.data);
                    onSuccess(ret.data.length);
                },
                onFailure);
        } else {

            // 获取检验人员列表-演示数据
            this.setData([
                {
                    userid: 'userid1',
                    username: 'username1',
                    departmentid:'departmentid1',
                    department:'department1',
                    usertype:'usertype1',
                },
                {
                    userid: 'userid2',
                    username: 'username2',
                    departmentid:'departmentid2',
                    department:'department2',
                    usertype:'usertype2',
                },
                {
                    userid: 'userid3',
                    username: 'username3',
                    departmentid:'departmentid3',
                    department:'department3',
                    usertype:'usertype3',
                },
                {
                    userid: 'userid4',
                    username: 'username4',
                    departmentid:'departmentid4',
                    department:'department4',
                    usertype:'usertype4',
                },
                {
                    userid: 'userid5',
                    username: 'username5',
                    departmentid:'departmentid5',
                    department:'department5',
                    usertype:'usertype5',
                }
            ]);

            onSuccess();
        }
    }

});