/*
 * File: app/store/common_getelevatorno.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.common_getelevatorno', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'common_getelevatorno',
        fields: [
            {
                name: 'elevatorno'
            },
            {
                name: 'floor'
            },
            {
                name: 'station'
            },
            {
                name: 'specno'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;
        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/common/api/1.0/getelevatorno';
            callPostAdapter(
                url, parm,
                function(ret) {
                    var d = ret.data;
                    var n = d.length;
                    for(var i=0; i<n; i++) {
                        me.add(d[i]);
                    }
                    onSuccess(n);
                },
            onFailure);
        } else {
            var start = parm.pageno, end = parm.pageno + parm.pagelen - 1;
            end = end>58? 58:end;

            for(var i=start; i<=end; i++) {
                this.add({
                    elevatorno: 'ELENO-5678-9012',
                    floor: '30',
                    station: '30',
                    specno: 'ELENO-5678',
                });
            }
            // 演示数据
            onSuccess(end - start + 1);
        }
    }

});