/*
 * File: app/store/common_projectlist.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.common_projectlist', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'common_projectlist',
        fields: [
            {
                name: 'projectid'
            },
            {
                name: 'projectname',
                type: 'string'
            },
            {
                name: 'projectaddress',
                type: 'string'
            },
            {
                name: 'elevatornum'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        console.log(parm);
        var me = this;
        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/common/api/1.0/ckxm';
            callPostAdapter(
                url, parm,
                function(ret) {
                    var d = ret.data;
                    var n = d.length;
                    for(var i=0; i<n; i++) {
                        me.add(d[i]);
                    }
                    onSuccess(n);
                },
            onFailure);
        } else {
            var start = (parm.curpagenum-1)*parm.pagesize+1, end = start + parm.pagesize-1;

            for(var i=start; i<=end; i++) {
                this.add({
                    projectid:'',
                    projectname: '广州市中梯物联科技发展有限公司.' + i,
                    projectaddress: '广州市荔湾区黄沙大道144号大冶有色大厦903A室',
                    elevatornum:''
                });
            }
            // 演示数据
            onSuccess(end - start + 1);
        }
    }

});