/*
 * File: app/store/cu_cuscens.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.cu_cuscens', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'cu_cuscens',
        fields: [
            {
                name: 'custid'
            },
            {
                name: 'custname'
            },
            {
                name: 'principal'
            },
            {
                name: 'purveyor'
            },
            {
                name: 'address'
            },
            {
                name: 'mugaddress'
            },
            {
                name: 'phone'
            },
            {
                name: 'fax'
            },
            {
                name: 'postno'
            },
            {
                name: 'bank'
            },
            {
                name: 'accounts'
            },
            {
                name: 'identificationnumber'
            },
            {
                name: 'licensenumber'
            },
            {
                name: 'r13'
            },
            {
                name: 'rem1'
            },
            {
                name: 'levelid'
            },
            {
                name: 'typeid'
            },
            {
                name: 'r7'
            },
            {
                name: 'r6'
            },
            {
                name: 'r8'
            },
            {
                name: 'r9'
            },
            {
                name: 'creatorid'
            },
            {
                name: 'r2'
            },
            {
                name: 'createdept'
            },
            {
                name: 'linkerbean'
            },
            {
                name: 'flowuserlist'
            }
        ]
    },

    updateDat: function(onSuccess, onFailure, parm) {
        var me = this;
        console.log('调用客户保存接口：');
        console.log(parm);
        if(global.isWorklight()) {
            var url = '/adapters/mugcustomer/api/1.0/uporsavecustomer';
            callPostAdapter(
                url, parm,
                function(ret) {
                    if(ret.status.code===200) {
                        onSuccess();
                    } else {
                        console.log(ret.status.info);
                        onFailure(ret.status.info);
                    }
                },
                function() {
                    onFailure('(未知)');
                }
            );
        } else {
            onSuccess();
        }
    },

    deleteDat: function(onSuccess, onFailure, parm) {
        var me = this;
        console.log('调用客户删除接口：');
        console.log(parm);
        if(global.isWorklight()) {
            var url = '/adapters/mugcustomer/api/1.0/delmugcustomer';
            callPostAdapter(
                url, parm,
                function(ret) {
                    if(ret.status.code===200) {
                        onSuccess(ret.data[0].info);
                    } else {
                        console.log(ret.status.info);
                        onFailure(ret.status.info);
                    }
                },
                function() {
                    onFailure('(未知)');
                }
            );
        } else {
            onSuccess('删除成功!');
        }
    }

});