/*
 * File: app/store/eng_kzfslist.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.eng_kzfslist', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'eng_kzfslist',
        fields: [
            {
                name: 'controlid'
            },
            {
                name: 'controlname'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;
        parm = {userid: global.getUserId()};

        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/firstcheck/api/1.0/kzfslist';
            callPostAdapter(
                url, parm,
                function(ret) {
                    me.setData(ret.data);
                    onSuccess(ret.data.length);
                },
                onFailure);
        } else {

            // 获取受信来源列表-演示数据
            this.setData([
                {
                    controlid: '1',
                    controlname: '单控'
                },
                {
                    controlid: '2',
                    controlname: '并联'
                },
                {
                    controlid: '3',
                    controlname: '群控'
                }
            ]);
                onSuccess(3);
                }
    }

});