/*
 * File: app/store/eng_elevatorfile_cl.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.eng_elevatorfile_cl', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'eng_elevatorfile_cl',
        fields: [
            {
                name: 'userid'
            },
            {
                name: 'prono'
            }
        ]
    },

    updateDat: function(onSuccess, onFailure, parm) {
        var me = this;
        console.log('调用电梯删除接口：');
        console.log(parm);
        if(global.isWorklight()) {
            var url = '/adapters/common/api/1.0/deleteliftinfo';
            callPostAdapter(
                url, parm,
                function(ret) {
                    if(ret.status.code===200) {
                        onSuccess(ret.data[0].info);
                    } else {
                        console.log(ret.status.info);
                        onFailure(ret.status.info);
                    }
                },
                function() {
                    onFailure('(未知)');
                }
            );
        } else {
            onSuccess('删除电梯('+parm.prono+')成功!');
        }
    }

});