/*
 * File: app/store/eng_lifttypelist.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.eng_lifttypelist', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'eng_lifttypelist',
        fields: [
            {
                name: 'typeid'
            },
            {
                name: 'typename'
            },
            {
                name: 'r1'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;
        parm = {userid: global.getUserId()};

        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/firstcheck/api/1.0/dtfllist';
            callPostAdapter(
                url, parm,
                function(ret) {
                    me.setData(ret.data);
                    onSuccess(ret.data.length);
                },
                onFailure);
        } else {

            // 获取电梯类型类型列表-演示数据
            this.setData([
                {
                    typeid: '1',
                    typename: '电梯类型1',
                    r1:'3310'
                },
                {
                    typeid: '2',
                    typename: '电梯类型2',
                    r1:'3320'
                },
                {
                    typeid: '3',
                    typename: '电梯类型3',
                    r1:'3330'
                }


            ]);
                onSuccess(3);
                }
    }

});