/*
 * File: app/store/eng_liftprovinciallevelid.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.eng_liftprovinciallevelid', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'eng_liftprovinciallevelid',
        fields: [
            {
                name: 'areaid'
            },
            {
                name: 'areaname'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;
        // console.log('查省份传去后台的参数:');
        // console.log(parm);

        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/firstcheck/api/1.0/szqylist';
            callPostAdapter(
                url, parm,
                function(ret) {
                    me.setData(ret.data);
                    onSuccess(ret.data.length);
                },
                onFailure);
        } else {

            // 获取地区区域列表-演示数据

             this.setData([
                 {
                    areaid :'110000',
                    areaname: '北京市',
                 },
                 {
                    areaid :'550000',
                    areaname: '测试省份2',
                 },
                 {
                    areaid :'660000',
                    areaname: '测试省份3',
                 },
                 {
                    areaid :'770000',
                    areaname: '测试省份4',
                 },
                 {
                    areaid :'880000',
                    areaname: '测试省份5',
                 },
             ]);
            // 演示数据
            onSuccess(4);


                }
    }

});