/*
 * File: app/store/first_check_job_handler.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.first_check_job_handler', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'first_check_job_handler',
        fields: [
            {
                name: 'userid'
            },
            {
                name: 'jnl'
            },
            {
                name: 'state'
            },
            {
                name: 'remark'
            },
            {
                name: 'sj'
            }
        ]
    },

    updateDat: function(onSuccess, onFailure, parm) {
        var me = this;
        console.log('调用派工单处理接口：');
        console.log(parm);
        if(global.isWorklight()) {
            var url = '/adapters/firstcheck/api/1.0/fcdopration';
            callPostAdapter(
                url, parm,
                function(ret) {
                    if(ret.status.code===200) {
        //                 console.log(ret.trno);
        //                 onSuccess(ret.trno);
                    } else {
                        console.log(ret.status.info);
                        onFailure(ret.status.info);
                    }
                },
                function() {
                    onFailure('(未知)');
                }
            );
        } else {
            onSuccess('TRNO-TEST12345');
        }
    }

});