/*
 * File: app/store/mainpage_dqdatasta.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.mainpage_dqdatasta', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'mainpage_dqdatasta',
        fields: [
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'deadlinecount',
                type: 'string'
            },
            {
                name: 'deadlinedate',
                type: 'string'
            },
            {
                name: 'titleIcon',
                type: 'string'
            },
            {
                name: 'unitname',
                type: 'string'
            },
            {
                name: 'cross',
                type: 'string'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;

        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/mainpage/api/1.0/dqdatasta';
            var userid = global.getUserId();
            var adapterParm = {userid: userid};

            callPostAdapter(
                url, adapterParm,
                function(ret) {
                    me.setData(ret.data);
                    onSuccess(ret.data.length);
                },
            onFailure);
        } else {
            // 首页-到期提醒-演示数据
            // 接口无提供字段：cross
            this.setData([
            {
                title: '到期应收电梯',
                deadlinecount: '12',
                titleIcon: 'ln ln-dollar',
                deadlinedate: '',
                cross: '30',
                unitname: '台'
            },
            {
                title: '即将到期合同',
                deadlinecount: '5',
                titleIcon: 'ln ln-contract',
                deadlinedate: '',
                cross: '50',
                unitname: '份'
            },
            {
                title: '本月年检电梯',
                deadlinecount: '118',
                titleIcon: 'ln ln-maintain',
                deadlinedate: '',
                cross: '65',
                unitname: '台'
            },
            {
                title: '操作证到期人数',
                deadlinecount: '12',
                titleIcon: 'ln ln-certificate',
                deadlinedate: '',
                cross: '20',
                unitname: '人'
            },
            ]);

            onSuccess(4);
        }
    },

    updateDat: function(onSuccess, onFailure, parm) {

    },

    filteDat: function(parm) {

    }

});