/*
 * File: app/store/reportsta_wbyjreportdetail_tdate.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.reportsta_wbyjreportdetail_tdate', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'reportsta_wbyjreportdetail_tdate',
        fields: [
            {
                name: 'zhilift',
                type: 'string'
            },
            {
                name: 'fulift',
                type: 'string'
            },
            {
                name: 'allcount',
                type: 'string'
            },
            {
                name: 'pricesum',
                type: 'string'
            },
            {
                name: 'price',
                type: 'string'
            },
            {
                name: 'withdraw',
                type: 'string'
            },
            {
                name: 'xubaonum',
                type: 'string'
            },
            {
                name: 'xubaoprice',
                type: 'string'
            },
            {
                name: 'xubaocount',
                type: 'string'
            },
            {
                name: 'timeoutnum',
                type: 'string'
            },
            {
                name: 'timeprice',
                type: 'string'
            },
            {
                name: 'timeoutcount',
                type: 'string'
            },
            {
                name: 'newnum',
                type: 'string'
            },
            {
                name: 'newprice',
                type: 'string'
            },
            {
                name: 'newcount',
                type: 'string'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm) {
        //console.log(parm);
        var me = this;

        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/reportsta/api/1.0/wbyjreportdetail';
            var userid = global.getUserId();
            var adapterParm = {userid: userid, date: parm};

            callPostAdapter(
                url, adapterParm,
                function(ret) {
                    me.setData(ret.data);
                    onSuccess(1);
                },
            onFailure);
        } else {
            // 维保业绩报表-演示数据
            this.setData([
                {
                    zhilift: '300',//直梯数量,
                    fulift: '10',//扶梯数量,
                    allcount: '310',//电梯总量,
                    pricesum: '37200.00',//总金额,
                    price: '1200.00',//维保电梯平均单价,
                    withdraw: '0',//退保数量,
                    xubaonum: '310',//续保数量,
                    xubaoprice: '1200.00',//续保电梯平均单价,
                    xubaocount: '37200.00',//续保总金额,
                    timeoutnum: '18',//到期电梯数量,
                    timeprice: '1200.00',//到期电梯平均单价,
                    timeoutcount: '21600.00',//到期电梯总金额,
                    newnum: '20',//新签电梯数量,
                    newprice: '1200.00',//新签电梯平均单价,
                    newcount: '24000.00',//新签电梯总金额
                }
            ]);

            onSuccess(1);
        }
    },

    updateDat: function(onSuccess, onFailure, parm) {

    },

    filteDat: function(parm) {

    }

});