/*
 * File: app/store/setting_message.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.setting_message', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'setting_message',
        fields: [
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'Topic',
                type: 'string'
            },
            {
                name: 'content',
                type: 'string'
            },
            {
                name: 'date',
                type: 'string'
            },
            {
                name: 'opername',
                type: 'string'
            },
            {
                name: 'msgtype',
                type: 'string'
            }
        ]
    },

    /*

        加载公告

    */
    loadDat: function(onSuccess, onFailure, parm) {
        var me = this;
        this.setData([]);

        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/common/api/1.0/appmessagge';
            var userid = global.getUserId();
            var adapterParm = {userid: userid};

            callPostAdapter(
                url, adapterParm,
                function(ret) {
                    if(ret.status.code!=200){
                        onFailure('读取公告列表失败');
                    }else{
                        me.setData(ret.data);
                        onSuccess(ret.data.length);
                    }
                },
                function() {
                    onFailure('读取公告列表失败');
                }
                );
        //         function(ret) {
        //             me.setData(ret.data);
        //             onSuccess(ret.data.length);
        //         },
        //     onFailure);
        } else {
            // 消息列表-演示数据
            this.setData([
        //         {
        //             title: '公司公告',
        //             content: '系统今晚24点停机维护,请大家做好数据备份。',
        //             opername: '管理员',
        //             date: '2015-06-17',
        //             msgtype:'1'
        //         },
        //         {
        //             title: '系统公告',
        //             content: '系统今晚24点停机维护,请大家做好数据备份。',
        //             opername: '管理员',
        //             date: '2015-06-13',
        //             msgtype:'0'
        //         },
        //         {
        //             title: '公司公告',
        //             content: '系统今晚24点停机维护,请大家做好数据备份。',
        //             opername: '管理员',
        //             date: '2015-06-11',
        //             msgtype:'1'
        //         },
        //         {
        //             title: '系统公告',
        //             content: '系统今晚24点停机维护,请大家做好数据备份。',
        //             opername: '管理员',
        //             date: '2015-06-17',
        //             msgtype:'0'
        //         },
        //         {
        //             title: '公司公告',
        //             content: '系统今晚24点停机维护,请大家做好数据备份。',
        //             opername: '管理员',
        //             date: '2015-06-13',
        //             msgtype:'1'
        //         },
        //         {
        //             title: '系统公告',
        //             content: '系统今晚24点停机维护,请大家做好数据备份。',
        //             opername: '管理员',
        //             date: '2015-06-11',
        //             msgtype:'0'
        //         },
        //         {
        //             title: '公司公告',
        //             content: '系统今晚24点停机维护,请大家做好数据备份。',
        //             opername: '管理员',
        //             date: '2015-06-17',
        //             msgtype:'1'
        //         },
        //         {
        //             title: '系统公告',
        //             content: '系统今晚24点停机维护,请大家做好数据备份。',
        //             opername: '管理员',
        //             date: '2015-06-13',
        //             msgtype:'0'
        //         },
        //         {
        //             title: '公司公告',
        //             content: '系统今晚24点停机维护,请大家做好数据备份。',
        //             opername: '管理员',
        //             date: '2015-06-11',
        //             msgtype:'1'
        //         }
            ]);

            onSuccess(0);
        }
    },

    updateDat: function(onSuccess, onFailure, parm) {

    },

    filteDat: function(parm) {
        this.clearFilter();
        if(parm!=='') {//分类显示
            this.filterBy(function(item) {
                var s = item.get('msgtype');
                return parm==s;
            });
        }
    }

});