/*
 * File: app/store/sx_reportlist.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.store.sx_reportlist', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        storeId: 'sx_reportlist',
        fields: [
            {
                name: 'rpno'
            },
            {
                name: 'projectname'
            },
            {
                name: 'addr'
            },
            {
                name: 'rptime'
            },
            {
                name: 'state'
            },
            {
                name: 'nextstate'
            },
            {
                name: 'color'
            }
        ]
    },

    loadDat: function(onSuccess, onFailure, parm, action) {
        var me = this;
        //console.log(JsonUtil.convertToString(parm));
        if(global.isWorklight()) {
            // adapter取数
            var url = '/adapters/rpt/api/1.0/rptlist';
            callPostAdapter(
                url, parm,
                function(ret) {
                    var info;
                    if(ret.status.code!=200){
                        if(parm.searchkey!==''){
                            onFailure('搜索故障报告失败');
                            return;
                        }
                        onFailure('读取故障报告列表失败');
                    }else{
                        if(ret.data.length===0){
                            if(parm.curpagenum===1){
                                switch(action){
                                    case 'refresh':
                                        info = '没有故障报告数据';
                                        break;
                                    case 'loadmore':
                                        break;
                                    case 'firstload':
                                        info = '没有故障报告数据';
                                        break;
                                    case 'search':
                                        info = '没有相关故障报告数据';
                                        break;
                                }

                                me.setData(ret.data);
                                onFailure(info);
        //                         onFailure('没有故障报告数据！');
                            }else{
                                onFailure('没有更多数据！');
                            }
                            return;
                        }
                        var d = me.decoDat(ret.data);
                        //第一次加载直接设置数据
                        if(parm.curpagenum==1){
                            me.setData(d);
                        }else{
                            //分页用法，在原有数据上继续添加
                            var n = d.length;
                            for(var i=0; i<n; i++) {
                                me.add(d[i]);
                            }
                        }
                        if(action==='loadmore'){
                            onSuccess(d.length);
                        }else{
                            onSuccess('resetCurPage');
                        }
        //                 onSuccess(d.data);
                    }
                },
                function() {
                    var info;
                    switch(action){
                        case 'refresh':
                            info = '刷新故障报告数据失败';
                            break;
                        case 'loadmore':
                            info = '加载更多故障报告数据失败';
                            break;
                        case 'firstload':
                            info = '获取故障报告数据失败';
                            break;
                        case 'search':
                            info = '搜索故障报告失败';
                            break;
                    }
                    onFailure(info);
        //             onFailure('读取故障报告列表失败');
                }
            );
        //         function(ret) {
        //             var d = me.decoDat(ret.data);
        //             me.setData(d);
        //             onSuccess(d.length);
        //         },
        //         onFailure);
        } else {

            //分页模拟
            var start = (parm.curpagenum-1)*20,
                end = parm.curpagenum * parm.pagesize;
            //         end = end>50?50:end;
            if(end>60){
                onFailure('没有更多数据！');
                return;
            }

            for(var i=start; i<end; i++) {
                this.add({
                    trno:'trno'+(i),
                    rpno:'rpno'+(i),
                    rptime:'2015-12-01 10:0'+i,
                    state:'待审',
                    projectname: '广州市华越友联科技发展有限公司.' + (i + 1),
                    addr: '广州市荔湾区黄沙大道144号大冶有色大厦1001室',
                    nextstate: [
                        {name:"同意",state:'同意'},
                        {name:"不同意",state:'不同意'},
                    ],
                });
            }
            // 演示数据
            onSuccess(end - start + 1);

            // 故障业务-故障报告书列表-演示数据
        //     var d = this.decoDat([
        //         {
        //             rpno:			'20151201001', //报告编号
        //             projectname:		'广州市华越友联科技发展有限公司',
        //             addr:			'故障地址',
        //             rptime:			'2015-12-01 10:00:00', //报告时间
        //             state:			'新建', //处理状态(当前状态)
        //             nextstate: [
        //                 {name:"提交",state:''}
        //             ],
        //         },
        //         {
        //             rpno:			'20151201002', //报告编号
        //             projectname:		'广州市荔湾区黄沙大道4号逸翠湾',
        //             addr:			'故障地址',
        //             rptime:			'2015-12-01 10:00:00', //报告时间
        //             state:			'待审', //处理状态(当前状态)
        //             nextstate: [
        //                 {name:"提交",state:''}
        //             ],
        //         },
        //         {
        //             rpno:			'20151201003', //报告编号
        //             projectname:		'广州市华越友联科技发展有限公司',
        //             addr:			'故障地址',
        //             rptime:			'2015-12-01 10:00:00', //报告时间
        //             state:			'通过', //处理状态(当前状态)
        //             nextstate: [
        //             ],
        //         },
        //         {
        //             rpno:			'20151201003', //报告编号
        //             projectname:		'广州市华越友联科技发展有限公司',
        //             addr:			'故障地址',
        //             rptime:			'2015-12-01 10:00:00', //报告时间
        //             state:			'不通过', //处理状态(当前状态)
        //             nextstate: [
        //             ],
        //         },
        //     ]
        //         );
        //         this.setData(d);
        //         onSuccess(d.length);
                }
    },

    filteDat: function(parm) {
        this.clearFilter();

        if(parm!=='') {
            this.filterBy(function(item) {
                var s = item.get("unitname") + ' ' + item.get("addr");
                return (s.toUpperCase().indexOf(parm.toUpperCase())>=0);
            });
        }
    },

    decoDat: function(data) {
        if(!data) return([]);

        for(var i=0;i<data.length; i++) {
            switch(data[i].state) {
                case '新建':
                    data[i].color = 'liftnet-fontColor-gray';
                    break;

                case '待审':
                    data[i].color = 'liftnet-fontColor-green';
                    break;

                case '通过':
                    data[i].color = 'liftnet-fontColor-orange';
                    break;

                case '不通过':
                    data[i].color = 'liftnet-fontColor-red';
                    break;
            }
        }

        return(data);
    }

});