/*
 * File: app/controller/Engineer/EngProjectTrackingController.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.controller.Engineer.EngProjectTrackingController', {
    extend: 'Ext.app.Controller',

    config: {
        control: {
            "container#EngProjectTrackingList": {
                initialize: 'onEngProjectTrackingListInitialize'
            },
            "button#EngProjectTracking_ReturnBt": {
                tap: 'onEngProjectTracking_ReturnBtTap'
            },
            "button#ProjectTracking_PStatus": {
                tap: 'onProjectTracking_PStatusTap'
            },
            "button#ProjectTrackingStatus_0": {
                tap: 'onProjectTrackingStatus_0Tap'
            },
            "button#ProjectTrackingStatus_1": {
                tap: 'onProjectTrackingStatus_1Tap'
            },
            "button#ProjectTrackingStatus_2": {
                tap: 'onProjectTrackingStatus_2Tap'
            },
            "button#ProjectTrackingStatus_3": {
                tap: 'onProjectTrackingStatus_3Tap'
            },
            "button#ProjectTrackingStatus_4": {
                tap: 'onProjectTrackingStatus_4Tap'
            },
            "button#ProjectTrackingStatus_5": {
                tap: 'onProjectTrackingStatus_5Tap'
            },
            "datepickerfield#ProjectTracking_Data1": {
                change: 'onProjectTracking_Data1Change'
            },
            "datepickerfield#ProjectTracking_Data2": {
                change: 'onProjectTracking_Data2Change'
            },
            "list#EngProjectTracking_SearchList": {
                itemtap: 'onEngProjectTracking_SearchListItemTap'
            },
            "panel#EngProjectTrackingDisPlay": {
                initialize: 'onEngProjectTrackingDisPlayInitialize'
            },
            "searchfield#ProjectTracking_SearchKey": {
                change: 'onProjectTracking_SearchKeyChange'
            },
            "button#EngProjectTracking_BtnAdd": {
                tap: 'onEngProjectTracking_BtnAddTap'
            },
            "textfield#ProjectTracking_add_coordinates": {
                tap: 'onProjectTracking_add_coordinatesTap'
            },
            "textfield#ProjectTracking_add_upcustname": {
                tap: 'onProjectTracking_add_upcustnameTap'
            },
            "textfield#ProjectTracking_add_custname": {
                tap: 'onProjectTracking_add_custnameTap'
            }
        }
    },

    onEngProjectTrackingListInitialize: function(component, eOpts) {
        var me = this;

        ProjectCurPage = 0;
        pagesize = 20;

        var searchkey = Ext.getCmp('ProjectTracking_SearchKey').getValue();

        Ext.getCmp('EngProjectTracking_SearchList').getStore().removeAll();

        // 初始化下拉刷新、滑动按钮插件
        var ProjectList = Ext.getCmp('EngProjectTracking_SearchList');
        ProjectList.setPlugins(
            [
                {
                    autoSnapBack: false,
                    lastUpdatedText: '上次刷新:&nbsp;',
                    loadedText: '已刷新',
                    loadingText: '正在刷新项目跟踪...',
                    pullText: '下拉刷新...',
                    releaseText: '放开开始刷新...',
                    type: 'pullrefresh',
                    listeners : {
                        latestfetched : function() {
        //                     faultCurPage=1;
                            me.doProjectTracking_LoadList(
                                1,
                                pagesize,
                                searchkey,
                                'refresh'
                            );
                        }
                    }
                }
            ]
        );


        //监听滑动结束事件
        var ProjectScroller = ProjectList.getScrollable().getScroller();
        ProjectScroller.on('scrollend',function(scroll, x, y, eOpts){
            console.log(ProjectCurPage);
            if(ProjectCurPage===0){
                return;
             }
            //滑动到底部加载更多
            if(y+ProjectScroller.getContainerSize().y==ProjectScroller.getSize().y){
                console.log('loadmore');
                loadMask.show();
                var scrollparm = {
                    scroller:ProjectScroller,
                    x:x,
                    y:y+80//Item的高度+Tpl样式中各种边距
                };
                var keyword = Ext.getCmp('ProjectTracking_SearchKey').getValue();
                if(!keyword){
                    keyword='';
                }
                me.doProjectTracking_LoadList(
                    ++ProjectCurPage,
                    pagesize,
                    keyword,
                    'loadmore',
                    scrollparm);
            }
        });

        //初始化显示数据
        me.doProjectTracking_LoadList(
                                1,
                                pagesize,
                                searchkey,
                                'refresh'
                            );

    },

    onEngProjectTracking_ReturnBtTap: function(button, e, eOpts) {
        //返回上页
        viewUtil.goLast();
    },

    onProjectTracking_PStatusTap: function(button, e, eOpts) {
        //项目跟踪-项目状态筛选按钮
        popMenu.show('Engineer.EngProjectTrackingStatus', button);
    },

    onProjectTrackingStatus_0Tap: function(button, e, eOpts) {
        // 全部
        this.doProjectTrackingFilter(button.getText());
    },

    onProjectTrackingStatus_1Tap: function(button, e, eOpts) {
        // 新建
        this.doProjectTrackingFilter(button.getText());
    },

    onProjectTrackingStatus_2Tap: function(button, e, eOpts) {
        // 待审
        this.doProjectTrackingFilter(button.getText());
    },

    onProjectTrackingStatus_3Tap: function(button, e, eOpts) {
        // 退出跟进
        this.doProjectTrackingFilter(button.getText());
    },

    onProjectTrackingStatus_4Tap: function(button, e, eOpts) {
        // 暂停跟进
        this.doProjectTrackingFilter(button.getText());
    },

    onProjectTrackingStatus_5Tap: function(button, e, eOpts) {
        // 允许跟进
        this.doProjectTrackingFilter(button.getText());
    },

    onProjectTracking_Data1Change: function(datepickerfield, newDate, oldDate, eOpts) {
        //项目跟踪-创建开始时间改变时
        var me = this;
        var start = Date.parse(newDate);
        var end = Date.parse(Ext.getCmp('ProjectTracking_Data2').getValue());
        if(start>end){
            datepickerfield.setValue(oldDate);
            Ext.toast('请选择正确的日期区间');
            return;
        }
        var searchkey = Ext.getCmp('ProjectTracking_SearchKey').getValue();
        this.doProjectTracking_LoadList(1,20,searchkey,'refresh');
    },

    onProjectTracking_Data2Change: function(datepickerfield, newDate, oldDate, eOpts) {
        //项目跟踪-创建结束时间改变时
        var me = this;
        var start = Date.parse(Ext.getCmp('ProjectTracking_Data1').getValue());
        var end = Date.parse(newDate);
        if(start>end){
            datepickerfield.setValue(oldDate);
            Ext.toast('请选择正确的日期区间');
            return;
        }
        var searchkey = Ext.getCmp('ProjectTracking_SearchKey').getValue();
        this.doProjectTracking_LoadList(1,20,searchkey,'refresh');
    },

    onEngProjectTracking_SearchListItemTap: function(dataview, index, target, record, e, eOpts) {
        viewUtil.goNext('Engineer.EngProjectTrackingDisPlay', {record: record});
    },

    onEngProjectTrackingDisPlayInitialize: function(component, eOpts) {
        //初始化项目跟踪查看信息
        loadMask.show();

        var me = this;
        var userid = global.getUserId();
        var now = Ext.Date.format(new Date(), 'Y-m-d H:i');
        var position = map.getLocation().addr;
        if(!position || position==='') position = '(未知位置)';

        var taskrecord = component.initialConfig.parm.record;
        var projectjnlno = taskrecord.get('projectjnlno'); // 项目编号
        console.log('projectjnlno:');
        console.log(projectjnlno);

        var parm = {
            projectjnlno: projectjnlno,
            userid: userid
        };

        // 初始化下拉选择项目
        //dataUtil.createStore('common_sxsourcelist').loadDat(Ext.emptyFn,Ext.emptyFn);
        //dataUtil.createStore('common_getdeptlist').loadDat(Ext.emptyFn,Ext.emptyFn);

        // 取出项目跟踪明细数据
        var store = dataUtil.createStore('eng_projecttracking_detail');
        store.loadDat(
            function() {
                // 显示项目跟踪数据
                var record = store.getData().get(0);
                console.log('----后台获取信息start----');
                console.log(record);
                console.log('----后台获取信息end----');

                Ext.getCmp('ProjectTracking_Info').setRecord(record);


                var linkerlist = record.get('linkerlist');
                console.log('_____linkerlist____');
                console.log(linkerlist);
                console.log('_____linkerlist____');
                linkerlist = dataUtil.createStore('eng_projecttracking_detail_linkerlist').decoDat(linkerlist);
                dataUtil.createStore('eng_projecttracking_detail_linkerlist').setData(linkerlist);



                var flowinfolist = record.get('flowinfolist');
                console.log('_____flowinfolist____');
                console.log(flowinfolist);
                console.log('_____flowinfolist____');
                flowinfolist = dataUtil.createStore('eng_projecttracking_detail_flowinfolist').decoDat(flowinfolist);
                dataUtil.createStore('eng_projecttracking_detail_flowinfolist').setData(flowinfolist);

                var bycontract = record.get('bycontract');
                console.log('_____bycontract____');
                console.log(bycontract);
                console.log('_____bycontract____');
                bycontract = dataUtil.createStore('eng_projecttracking_detail_bycontract').decoDat(bycontract);
                dataUtil.createStore('eng_projecttracking_detail_bycontract').setData(bycontract);





                loadMask.hide();
            },
            function() {
                loadMask.hide();
                Ext.toast('读取项目跟踪资料失败！');
                viewUtil.goLast();
            },
            parm
        );
    },

    onProjectTracking_SearchKeyChange: function(textfield, newValue, oldValue, eOpts) {
        var ProjectTracking_Search = textfield.getValue();
        if(!ProjectTracking_Search||ProjectTracking_Search===''){
            ProjectTracking_Search = '';
        //     return;
        }
        //联网搜索
        // faultCurPage = 1;
        this.doProjectTracking_LoadList(1,20,ProjectTracking_Search,'refresh');
        // Ext.getCmp('EngFault_ListHotline').getStore().filteDat(Enfault_Search);
    },

    onEngProjectTracking_BtnAddTap: function(button, e, eOpts) {
        //进入新建界面
        // Ext.toast('项目跟踪新建功能正在开发中'+'<br><br>'+'敬请期待！');
        viewUtil.goNext('Engineer.EngProjectTrackingAdd',{});
    },

    onProjectTracking_add_coordinatesTap: function(textfield) {
        //选择坐标
        var lng = textfield.getValue().split(',')[0];
        var lat = textfield.getValue().split(',')[1];

        viewUtil.goNext('Common.ComMap', {
            lng : lng,
            lat : lat,
            fnClick: function(r2){
                textfield.setValue(r2);

            }
        });
    },

    onProjectTracking_add_upcustnameTap: function(textfield) {
        //上级单位选择
        var tpl =
        '<div class="liftnet-font-size14 liftnet-fontColor-darkGray">{custname}</div>';

        viewUtil.goNext('Common.ComSelect', {
            textfield: textfield,
            storeid: 'cu_culist',
            storeparm: {
                userid: global.getUserId(),
                searchkey: '',
                flowstatus:'%',
                curpagenum: 1,
                pagesize: 20
            },
            itemtpl: tpl,
            paging: true,
            allowedit: false,
            allowsearch: true,
            fnSetFilter: function(parm, text) {
                parm.searchkey = text;
                return parm;
            },
            fnSelected: function(record) {
                if(typeof(record)==='string') {
                    textfield.setValue(record);
                } else {
                    var value = record.get('custname');
                    textfield.setValue(value);
                }
            }
        });
        textfield.blur();
    },

    onProjectTracking_add_custnameTap: function(textfield) {
        //客户名称选择
        var tpl =
        '<div class="liftnet-font-size14 liftnet-fontColor-darkGray">{custname}</div>';

        viewUtil.goNext('Common.ComSelect', {
            textfield: textfield,
            storeid: 'cu_culist',
            storeparm: {
                userid: global.getUserId(),
                searchkey: '',
                flowstatus:'%',
                curpagenum: 1,
                pagesize: 20
            },
            itemtpl: tpl,
            paging: true,
            allowedit: true,
            allowsearch: true,
            fnSetFilter: function(parm, text) {
                parm.searchkey = text;
                return parm;
            },
            fnSelected: function(record) {
                if(typeof(record)==='string') {
                    textfield.setValue(record);
                    Ext.getCmp('ProjectTracking_add_ob2').setValue('');
                } else {
                    var value = record.get('custname');
                    textfield.setValue(value);
                    Ext.getCmp('ProjectTracking_add_ob2').setValue(record.get('custid'));
                    Ext.getCmp('ProjectTracking_add_custaddress').setValue(record.get('address'));
                }
            }
        });
        textfield.blur();
    },

    doProjectTracking_LoadList: function(page, pagesize, searchkey, action, scrollparm) {
        //项目跟踪标签页 - 项目跟踪列表刷新

        if(Ext.getCmp('EngProjectTracking_SearchList')){

        var flowstatus = '';
        var flowstatusT = Ext.getCmp('ProjectTracking_PStatus').getText();
        switch(flowstatusT){
            case '全部':
                flowstatus='%';
                break;
            case '新建':
                flowstatus='1';
                break;
            case '待审':
                flowstatus='2';
                break;
            case '退回跟进':
                flowstatus='3';
                break;
            case '暂停跟进':
                flowstatus='4';
                break;
            case '允许跟进':
                flowstatus='5';
                break;

        }


        var startdate = Ext.getCmp('ProjectTracking_Data1').getValue()===null?'1980-01-01':
        Ext.Date.format(Ext.getCmp('ProjectTracking_Data1').getValue(),'Y-m-d');

        var enddate = Ext.getCmp('ProjectTracking_Data2').getValue()===null?'2020-01-01':
        Ext.Date.format(Ext.getCmp('ProjectTracking_Data2').getValue(),'Y-m-d');

         if(searchkey==='')
           searchkey = Ext.getCmp('ProjectTracking_SearchKey').getValue();

        var parm = {
            userid: global.getUserId(),
            curpagenum:page,
            pagesize:pagesize,
            searchkey:searchkey,
            startdate:startdate,
            enddate:enddate,
            flowstatus:flowstatus
        };

        console.log('----传到后台的参数----');
        console.log(parm);
        console.log('----传到后台的参数----');

        Ext.getCmp('EngProjectTracking_SearchList').getStore().loadDat(
            function(n) {
                if(scrollparm){
                     scrollparm.scroller.scrollTo(scrollparm.x,scrollparm.y);
                     loadMask.hide();
                }
                if(n==='resetCurPage'){
                    ProjectCurPage = 1;
                }
                console.log('项目跟踪搜索完成!');
            },
            function(info) {
                Ext.toast(info);
                if(info==='加载更多项目跟踪数据失败'){
                    ProjectCurPage--;
                }
                if(info==='没有更多数据！'){
                    ProjectCurPage = 0;//没有更多数据的时候重置页数为0，不触发上拉事件
                }
        //         if(faultCurPage!=1){
        //              faultCurPage--;//获取数据失败页数减一
        //         }
                loadMask.hide();
            },
            parm,
            action
        );
        }
    },

    doProjectTrackingFilter: function(filter) {
        popMenu.getShowBy().setText(filter);
        popMenu.hide();
        var searchkey = Ext.getCmp('ProjectTracking_SearchKey').getValue();
        this.doProjectTracking_LoadList(1,20,searchkey,'refresh');
    }

});