/*
 * File: app/view/Admin/AdmAudSwspdetail.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Admin.AdmAudSwspdetail', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Spacer',
        'Ext.tab.Panel',
        'Ext.form.Panel',
        'Ext.field.TextArea',
        'Ext.dataview.List',
        'Ext.XTemplate'
    ],

    config: {
        id: 'AdmAudSwspdetail',
        layout: 'vbox',
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                title: '商务审批审核',
                items: [
                    {
                        xtype: 'button',
                        id: 'AdmAudSwspdetail_ButReturn',
                        iconCls: 'fa fa-chevron-left'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        hidden: true,
                        iconCls: 'fa fa-search'
                    }
                ]
            },
            {
                xtype: 'tabpanel',
                flex: 1,
                cls: 'liftnet-tabbar-two',
                items: [
                    {
                        xtype: 'container',
                        title: '主要信息',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'formpanel',
                                flex: 1,
                                cls: [
                                    'liftnet-form-info',
                                    'liftnet-font-size14',
                                    'liftnet-lineHeight34'
                                ],
                                id: 'form_aud_swspdetail',
                                items: [
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '甲方单位',
                                        name: 'custid',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '项目名称',
                                        labelWidth: '50%',
                                        name: 'projectname',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '施工地址',
                                        labelWidth: '50%',
                                        name: 'quoteaddress',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '付款方式',
                                        labelWidth: '40%',
                                        name: 'r13',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '报价日期',
                                        labelWidth: '50%',
                                        name: 'quotedate',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '经办人',
                                        labelWidth: '40%',
                                        name: 'operationid',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '客户特殊约定',
                                        labelWidth: '40%',
                                        name: 'custspecassu',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '备注',
                                        labelWidth: '40%',
                                        name: 'rem',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '保养开始日期',
                                        labelWidth: '40%',
                                        name: 'r9',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '保养结束日期',
                                        labelWidth: '40%',
                                        name: 'r10',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '保养月数',
                                        labelWidth: '40%',
                                        name: 'r18',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '台数',
                                        labelWidth: '40%',
                                        name: 'allcount',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '总价',
                                        labelWidth: '40%',
                                        name: 'r16',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '申请项目',
                                        labelWidth: '40%',
                                        name: 'citemid',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '原因说明',
                                        labelWidth: '40%',
                                        name: 'causerec',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textfield',
                                        clearIcon: false,
                                        label: '原因分析',
                                        labelWidth: '40%',
                                        name: 'causeanalyse',
                                        readOnly: true
                                    },
                                    {
                                        xtype: 'textareafield',
                                        clearIcon: false,
                                        label: '审批意见',
                                        name: 'audrem',
                                        placeHolder: '请输入审批意见'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        title: '明细列表',
                        layout: 'vbox',
                        items: [
                            {
                                xtype: 'list',
                                flex: 1,
                                cls: 'liftnet-aApprove-listBox',
                                id: 'AdmAudswspdetail_ListDetailed',
                                disableSelection: true,
                                itemTpl: [
                                    '<div class="liftnet-aApprove-listConBox">',
                                    '	<div class="liftnet-aApprove-listConBox-top liftnet-font-size16 liftnet-fontColor-darkGray">',
                                    '电梯类型:{eletype}</div>',
                                    '    <div class="liftnet-fontColor-gray liftnet-font-size12">台数：{num}台</div>',
                                    '    <div class="liftnet-fontColor-gray liftnet-font-size12">合计:{countprice}元</div>',
                                    '</div>'
                                ],
                                pressedCls: ' ',
                                onItemDisclosure: true
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: [
                    'liftnet-button',
                    'liftnet-button-two'
                ],
                id: 'AdmAudswsp_PnlYesNo',
                items: [
                    {
                        xtype: 'button',
                        docked: 'left',
                        id: 'AdmAudSwspdetail_BtnYes',
                        text: '同意'
                    },
                    {
                        xtype: 'button',
                        docked: 'right',
                        id: 'AdmAudSwspdetail_BtnNo',
                        text: '不同意'
                    }
                ]
            }
        ]
    }

});