/*
 * File: app/view/Admin/AdmHome.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Admin.AdmHome', {
    extend: 'Ext.tab.Panel',

    requires: [
        'Ext.Button',
        'Ext.Spacer',
        'Ext.Label',
        'Ext.Img',
        'Ext.XTemplate',
        'Ext.form.Panel',
        'Ext.field.Search',
        'Ext.dataview.List',
        'Ext.tab.Panel',
        'Ext.tab.Bar'
    ],

    config: {
        id: 'AdmHome',
        layout: {
            type: 'card',
            animation: false
        },
        items: [
            {
                xtype: 'container',
                title: '首页',
                iconCls: 'ln ln-home',
                cls: 'liftnet-aHome',
                id: 'AdmHome_Home',
                layout: 'vbox',
                scrollable: true,
                items: [
                    {
                        xtype: 'toolbar',
                        cls: 'liftnet-toolbar-home',
                        docked: 'top',
                        title: '首页',
                        items: [
                            {
                                xtype: 'button',
                                id: 'AdmHome_btnNav',
                                iconCls: 'ln ln-menu'
                            },
                            {
                                xtype: 'button',
                                id: 'AdmHome_btnSwitch',
                                itemId: 'AdmHome_btnSwitch',
                                iconCls: 'ln ln-user'
                            },
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                id: 'AdmHome_btnRefresh',
                                iconCls: 'ln ln-refresh'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: 'liftnet-aHome-topbox',
                        height: 120,
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'liftnet-font-center',
                                docked: 'left',
                                width: 100,
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'liftnet-fontColor-green',
                                            'liftnet-font-size24',
                                            'liftnet-aHome-topbox-number'
                                        ],
                                        hidden: true,
                                        html: '23',
                                        id: 'approvecount'
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'liftnet-fontColor-gray',
                                            'liftnet-font-size14'
                                        ],
                                        hidden: true,
                                        html: '待办'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'liftnet-font-center',
                                items: [
                                    {
                                        xtype: 'image',
                                        cls: [
                                            'liftnet-border-radius50',
                                            'liftnet-aHome-topbox-icon'
                                        ],
                                        id: 'AdmHome_ImgAvator',
                                        src: 'resources/images/home_icon02.png'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'liftnet-font-center',
                                docked: 'right',
                                width: 100,
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'liftnet-fontColor-green',
                                            'liftnet-font-size24',
                                            'liftnet-aHome-topbox-number'
                                        ],
                                        hidden: true,
                                        html: '52',
                                        id: 'checkcount'
                                    },
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'liftnet-fontColor-gray',
                                            'liftnet-font-size14'
                                        ],
                                        hidden: true,
                                        html: '审批'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'liftnet-font-center',
                                docked: 'bottom',
                                items: [
                                    {
                                        xtype: 'label',
                                        cls: [
                                            'liftnet-aHome-topbox-user',
                                            'liftnet-fontColor-darkGray'
                                        ],
                                        html: '<i class="ln ln-settings"></i> Admin',
                                        id: 'AdmHome_LblUserName'
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        cls: [
                            'liftnet-home-fontScroll',
                            'liftnet-fontColor-green',
                            'liftnet-font-size14',
                            'liftnet-home-rolling'
                        ],
                        docked: 'bottom',
                        height: 28,
                        itemId: 'mypanel1',
                        items: [
                            {
                                xtype: 'panel',
                                docked: 'left',
                                margin: '0 0 0 3%',
                                width: '27%',
                                items: [
                                    {
                                        xtype: 'label',
                                        html: '<i class="fa fa-volume-up"></i> 最新发布:'
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                docked: 'left',
                                html: '<marquee style="WIDTH: 100%;" scrollamount="2"  direction="left"><font></font ></marquee >',
                                id: 'AdmHome_PnlNotice',
                                margin: '0 3% 0 0',
                                width: '67%'
                            }
                        ],
                        listeners: [
                            {
                                fn: function(component, eOpts) {
                                    this.element.on({
                                        tap: function() {
                                            viewUtil.goNext('Common.ComHomeNews');
                                        }
                                    });
                                },
                                event: 'initialize'
                            }
                        ]
                    },
                    {
                        xtype: 'dataview',
                        cls: 'liftnet-aHome-data',
                        height: 290,
                        id: 'AdmHome_DvData',
                        scrollable: false,
                        itemTpl: [
                            '	<div class="liftnet-aHome-dataBox liftnet-aHome-dataBox-{color}">',
                            '        <div class="liftnet-aHome-dataBox-numberBox liftnet-fontColor-white">',
                            '            <div class="liftnet-aHome-dataBox-icon"><i class="fa fa-{titleIcon}"></i></div>',
                            '            <div class="liftnet-aHome-dataBox-number">{count}</div>',
                            '        </div>',
                            '        <div class="liftnet-aHome-dataBox-titleBox">{title}({unitname})</div>',
                            '     </div>'
                        ],
                        store: 'mainpage_htdatasta'
                    },
                    {
                        xtype: 'container',
                        cls: 'liftnet-aHome-map',
                        height: 280,
                        hidden: true,
                        html: '<div class="liftnet-shade"></div><div id="admHomeMap"  style="height:100%;width:100%;"></div>',
                        id: 'AdmHome_Map',
                        itemId: 'mycontainer3',
                        listeners: [
                            {
                                fn: function(element, eOpts) {
                                    this.fireEvent('painted', this);
                                },
                                event: 'painted'
                            }
                        ]
                    },
                    {
                        xtype: 'dataview',
                        cls: 'liftnet-aHome-pie',
                        height: 270,
                        id: 'AdmHome_DvPie',
                        padding: '0 10',
                        scrollable: false,
                        itemTpl: [
                            '    <div class="liftnet-aHome-pieBox">',
                            '        <div class="liftnet-aHome-pieLeft" style=\'width:100% !important\'>',
                            '            <div style=\'float:left\' class="liftnet-aHome-pieLeft-title liftnet-font-size14">{title}</div>',
                            '            <div style=\'float:right; right:0\' class="liftnet-aHome-pieLeft-con liftnet-font-size12 liftnet-fontColor-gray">',
                            '                <div><span class="liftnet-bgColor-green"></span>通过{acceptcount}</div>',
                            '                <div><span class="liftnet-bgColor-blue"></span>待审{approvecount}</div>',
                            '                <div><span class="liftnet-bgColor-red"></span>新建{waitsubcount}</div>',
                            '            </div>',
                            '        </div>',
                            '        <!--div class="liftnet-aHome-pieRight"-->',
                            '            <!--canvas id="{pieid}" width="50" height="50"/-->',
                            '            <!--img src=\'resources/images/pie.jpg\' width="50" height="50" /-->',
                            '        <!--/div-->',
                            '    </div>'
                        ],
                        store: 'mainpage_shdatasta'
                    },
                    {
                        xtype: 'dataview',
                        cls: 'liftnet-aHome-cross',
                        height: 282,
                        id: 'AdmHome_DvCross',
                        padding: '0 10',
                        scrollable: false,
                        itemTpl: [
                            '    <div class="liftnet-aHome-crossBox">',
                            '        <div class="liftnet-home-crossBox-titleBox">',
                            '            <div class=" liftnet-aHome-crossBox-title liftnet-font-size14 liftnet-fontColor-darkGray liftnet-font-left"><i class="{titleIcon}"></i>{title}</div>',
                            '            <div class="liftnet-aHome-crossBox-numbe liftnet-font-size14 liftnet-font-right liftnet-fontColor-red">{deadlinecount}{unitname}</div>',
                            '        </div>',
                            '        <div class="liftnet-aHome-crossBox-percentBox liftnet-bgColor-gray">',
                            '            <div class="liftnet-aHome-crossBox-word liftnet-fontColor-gray liftnet-font-center liftnet-font-size12">{cross}%</div>',
                            '            <div class="liftnet-aHome-crossBox-percent liftnet-bgColor-green" style="width:{cross}%"></div>',
                            '        </div>',
                            '    </div>'
                        ],
                        store: 'mainpage_dqdatasta'
                    },
                    {
                        xtype: 'formpanel',
                        cls: 'liftnet-search-form',
                        id: 'AdmHome_PnlSearch',
                        scrollable: false,
                        items: [
                            {
                                xtype: 'searchfield',
                                cls: 'liftnet-font-size12',
                                itemId: 'AdmHome_FldSearch',
                                placeHolder: '输入关键词'
                            }
                        ]
                    },
                    {
                        xtype: 'dataview',
                        cls: 'liftnet-aHome-list',
                        height: 76,
                        id: 'AdmHome_DvList',
                        itemId: 'mydataview4',
                        scrollable: false,
                        itemTpl: [
                            '<div class="liftnet-aHome-listBox">',
                            '    	<div class="liftnet-aHome-listBox-titleBox">',
                            '        	<div class="liftnet-aHome-listBox-title liftnet-font-size14 liftnet-fontColor-darkGray">{titleIcon}{title}</div>',
                            '        	<div class="liftnet-aHome-listBox-state liftnet-font-size12 liftnet-font-right {statusColor}">{status} <i class="fa fa-circle-o"></i></div>',
                            '        </div>',
                            '        <div class="liftnet-aHome-listBox-conBox">',
                            '        <div class="liftnet-aHome-listBox-con liftnet-font-size12 liftnet-fontColor-gray">{key1}</div>',
                            '        <div class="liftnet-aHome-listBox-time liftnet-font-size12 liftnet-fontColor-gray liftnet-font-right"><i class="fa fa-clock-o"></i> {datetime}</div>',
                            '   </div>',
                            '</div>'
                        ],
                        store: 'mainpage_shdatalist'
                    }
                ]
            },
            {
                xtype: 'container',
                title: '报表',
                iconCls: 'fa fa-calendar-o',
                cls: 'liftnet-bgColor-gray',
                id: 'AdmReport',
                scrollable: true,
                items: [
                    {
                        xtype: 'toolbar',
                        cls: 'liftnet-toolbar-other',
                        docked: 'top',
                        title: '报表'
                    },
                    {
                        xtype: 'panel',
                        items: [
                            {
                                xtype: 'panel',
                                cls: 'liftnet-report-table',
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'liftnet-report-table-top',
                                            'liftnet-fontColor-red',
                                            'liftnet-bgColor-white'
                                        ],
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: '<i class="ln ln-contract"></i>热线受信报表'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        scrollable: 'false',
                                        cls: 'liftnet-report-table-lsitBox',
                                        id: 'AdmReport_DvHotline',
                                        disableSelection: true,
                                        itemTpl: [
                                            '<div class="liftnet-report-table-lsit">',
                                            '        <div class="liftnet-font-size14 liftnet-fontColor-darkGray">{title} {count}</div>',
                                            '        <div class="liftnet-font-size12 liftnet-fontColor-gray liftnet-report-table-lsitCon">',
                                            '            <div class="liftnet-float-left liftnet-margin-right12">困人宗数:{istrapcount}</div>',
                                            '            <div class="liftnet-float-left">统计时间:{stattime}</div>',
                                            '        </div>',
                                            '    </div>'
                                        ],
                                        store: 'reportsta_sxreportsta',
                                        onItemDisclosure: true
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'liftnet-report-table',
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'liftnet-report-table-top',
                                            'liftnet-fontColor-blue',
                                            'liftnet-bgColor-white'
                                        ],
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: '<i class="ln ln-report-maintain"></i>保养计划报表'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        scrollable: 'false',
                                        cls: 'liftnet-report-table-lsitBox',
                                        id: 'AdmReport_DvMaintain',
                                        disableSelection: true,
                                        itemTpl: [
                                            '<div class="liftnet-report-table-lsit">',
                                            '        <div class="liftnet-font-size14 liftnet-fontColor-darkGray">{title} {count}</div>',
                                            '        <div class="liftnet-font-size12 liftnet-fontColor-gray liftnet-report-table-lsitCon">',
                                            '            <div class="liftnet-float-left liftnet-margin-right12">已录入实绩数:{sjcount}</div>',
                                            '            <div class="liftnet-float-left">统计时间:{stattime}</div>',
                                            '        </div>',
                                            '    </div>'
                                        ],
                                        store: 'reportsta_byreportsta',
                                        onItemDisclosure: true
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'liftnet-report-table',
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'liftnet-report-table-top',
                                            'liftnet-fontColor-green',
                                            'liftnet-bgColor-white'
                                        ],
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: '<i class="fn ln-report-repair"></i>故障报告书报表'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        scrollable: 'false',
                                        cls: 'liftnet-report-table-lsitBox',
                                        id: 'AdmReport_DvFault',
                                        disableSelection: true,
                                        itemTpl: [
                                            '<div class="liftnet-report-table-lsit">',
                                            '        <div class="liftnet-font-size14 liftnet-fontColor-darkGray">{title} {count}</div>',
                                            '        <div class="liftnet-font-size12 liftnet-fontColor-gray liftnet-report-table-lsitCon">',
                                            '            <div class="liftnet-float-left  liftnet-margin-right12">统计时间:{stattime}</div>',
                                            '        </div>',
                                            '    </div>'
                                        ],
                                        store: 'reportsta_gzreportsta',
                                        onItemDisclosure: true
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                cls: 'liftnet-report-table',
                                items: [
                                    {
                                        xtype: 'panel',
                                        cls: [
                                            'liftnet-report-table-top',
                                            'liftnet-fontColor-orange',
                                            'liftnet-bgColor-white'
                                        ],
                                        items: [
                                            {
                                                xtype: 'label',
                                                html: '<i class="ln ln-report-service"></i>维保业绩报表'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'list',
                                        scrollable: 'false',
                                        cls: 'liftnet-report-table-lsitBox',
                                        id: 'AdmReport_DvPerformance',
                                        disableSelection: true,
                                        itemTpl: [
                                            '<div class="liftnet-report-table-lsit">',
                                            '        <div class="liftnet-font-size14 liftnet-fontColor-darkGray">{title} {count}</div>',
                                            '        <div class="liftnet-font-size12 liftnet-fontColor-gray liftnet-report-table-lsitCon">',
                                            '            <div class="liftnet-float-left liftnet-margin-right12">直梯台量:{zcount}</div>',
                                            '            <div class="liftnet-float-left">扶梯台量:{fcount}</div>',
                                            '        </div>',
                                            '    </div>'
                                        ],
                                        store: 'reportsta_wbyjreportsta',
                                        onItemDisclosure: true
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                xtype: 'container',
                title: '实时监控',
                iconCls: 'ln ln-monitor',
                cls: 'liftnet-monitor',
                id: 'AdmMonitor',
                itemId: 'mycontainer4',
                layout: 'vbox',
                items: [
                    {
                        xtype: 'toolbar',
                        cls: 'liftnet-toolbar-other',
                        docked: 'top',
                        title: '实时监控'
                    },
                    {
                        xtype: 'tabpanel',
                        flex: 1,
                        cls: 'liftnet-tabbar-one',
                        id: 'AdmHome_TPnlMonitor',
                        items: [
                            {
                                xtype: 'container',
                                title: '人员位置',
                                id: 'AdmHome_MapPeople',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        cls: 'liftnet-monitor-map',
                                        html: '<div class="liftnet-shade"></div><div id="peopleMap"  style="height:100%;width:100%;"></div>',
                                        id: 'Container_peopleMap',
                                        layout: 'vbox'
                                    },
                                    {
                                        xtype: 'formpanel',
                                        cls: [
                                            'liftnet-search-form',
                                            'liftnet-button-blue'
                                        ],
                                        docked: 'bottom',
                                        height: 54,
                                        scrollable: false,
                                        items: [
                                            {
                                                xtype: 'searchfield',
                                                cls: 'liftnet-font-size12',
                                                placeHolder: '员工姓名'
                                            },
                                            {
                                                xtype: 'button',
                                                docked: 'right',
                                                id: 'AdmMonitor_BtnPeople',
                                                width: 110,
                                                text: '查看所有人员'
                                            }
                                        ]
                                    }
                                ],
                                listeners: [
                                    {
                                        fn: function(element, eOpts) {
                                            this.fireEvent('painted', this);
                                        },
                                        event: 'painted'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                title: '电梯位置',
                                id: 'AdmHome_MapElevator',
                                layout: 'vbox',
                                items: [
                                    {
                                        xtype: 'container',
                                        flex: 1,
                                        cls: 'liftnet-monitor-map',
                                        html: '<div class="liftnet-shade"></div><div id="elevatorMap"  style="height:100%;width:100%;"></div>',
                                        id: 'Container_elevatorMap',
                                        layout: 'vbox'
                                    },
                                    {
                                        xtype: 'formpanel',
                                        cls: [
                                            'liftnet-search-form',
                                            'liftnet-button-blue'
                                        ],
                                        docked: 'bottom',
                                        height: 54,
                                        scrollable: false,
                                        items: [
                                            {
                                                xtype: 'searchfield',
                                                cls: 'liftnet-font-size12',
                                                placeHolder: '电梯注册码'
                                            },
                                            {
                                                xtype: 'button',
                                                docked: 'right',
                                                id: 'AdmMonitor_BtnLift',
                                                width: 110,
                                                text: '查看所有电梯'
                                            }
                                        ]
                                    }
                                ],
                                listeners: [
                                    {
                                        fn: function(element, eOpts) {
                                            this.fireEvent('painted', this);
                                        },
                                        event: 'painted'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ],
        tabBar: {
            cls: [
                'liftnet-tab',
                'liftnet-tab-33'
            ],
            docked: 'bottom'
        },
        listeners: [
            {
                fn: 'onAdmHome_btnSwitchTap',
                event: 'tap',
                delegate: '#AdmHome_btnSwitch'
            }
        ]
    },

    onAdmHome_btnSwitchTap: function(button, e, eOpts) {
        liftnet.app.getController('ComController').doHome_Switch();
    }

});