/*
 * File: app/view/Admin/AdmReportFault.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Admin.AdmReportFault', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Img',
        'Ext.Label',
        'Ext.form.Panel',
        'Ext.field.Text'
    ],

    config: {
        id: 'AdmReportFault',
        layout: 'vbox',
        scrollable: true,
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                title: '故障报告书报表',
                items: [
                    {
                        xtype: 'button',
                        id: 'AdmReportFault_BtnReturn',
                        iconCls: 'fa fa-chevron-left'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: [
                    'liftnet-font-center',
                    'liftnet-con-top'
                ],
                items: [
                    {
                        xtype: 'image',
                        cls: 'liftnet-con-icon',
                        src: 'resources/images/con_icon03.png'
                    },
                    {
                        xtype: 'label',
                        cls: [
                            'liftnet-fontColor-green',
                            'liftnet-font-size20'
                        ],
                        html: '正在载入...',
                        id: 'AdmReportFault_lblAllCount'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'liftnet-con-title',
                items: [
                    {
                        xtype: 'label',
                        html: '内容'
                    }
                ]
            },
            {
                xtype: 'formpanel',
                cls: [
                    'liftnet-form-info',
                    'liftnet-font-size14',
                    'liftnet-lineHeight34'
                ],
                height: 163,
                id: 'form_reportsta_gzreportdetail_tdate',
                scrollable: false,
                items: [
                    {
                        xtype: 'textfield',
                        hidden: true,
                        clearIcon: false,
                        labelWidth: '70%',
                        name: 'allcount',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '应录入故障报告书',
                        labelWidth: '70%',
                        name: 'needcount',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '已录入故障报告书宗数',
                        labelWidth: '70%',
                        name: 'hascount',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '已录入故障报告书率',
                        labelWidth: '70%',
                        name: 'haswriteper',
                        readOnly: true
                    }
                ]
            }
        ]
    }

});