/*
 * File: app/view/Admin/AdmReportPerformance.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.4.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.4.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('liftnet.view.Admin.AdmReportPerformance', {
    extend: 'Ext.Panel',

    requires: [
        'Ext.Toolbar',
        'Ext.Button',
        'Ext.Img',
        'Ext.Label',
        'Ext.form.Panel',
        'Ext.field.Text'
    ],

    config: {
        id: 'AdmReportPerformance',
        layout: 'vbox',
        scrollable: true,
        items: [
            {
                xtype: 'toolbar',
                cls: 'liftnet-toolbar-other',
                docked: 'top',
                title: '维保业绩报表',
                items: [
                    {
                        xtype: 'button',
                        id: 'AdmReportPerformance_BtnReturn',
                        iconCls: 'fa fa-chevron-left'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: [
                    'liftnet-font-center',
                    'liftnet-con-top'
                ],
                items: [
                    {
                        xtype: 'image',
                        cls: 'liftnet-con-icon',
                        src: 'resources/images/con_icon04.png'
                    },
                    {
                        xtype: 'label',
                        cls: [
                            'liftnet-fontColor-green',
                            'liftnet-font-size20'
                        ],
                        html: '正在载入...',
                        id: 'AdmReportPerformance_lblAllCount'
                    }
                ]
            },
            {
                xtype: 'panel',
                cls: 'liftnet-con-title',
                items: [
                    {
                        xtype: 'label',
                        html: '内容'
                    }
                ]
            },
            {
                xtype: 'formpanel',
                cls: [
                    'liftnet-form-info',
                    'liftnet-font-size14',
                    'liftnet-lineHeight34'
                ],
                height: 800,
                id: 'form_reportsta_wbyjreportdetail_tdate',
                scrollable: false,
                items: [
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '直梯数量',
                        labelWidth: '70%',
                        name: 'zhilift',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '扶梯数量',
                        labelWidth: '70%',
                        name: 'fulift',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '电梯总量',
                        labelWidth: '70%',
                        name: 'allcount',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '总金额',
                        labelWidth: '70%',
                        name: 'pricesum',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '维保电梯平均单价',
                        labelWidth: '70%',
                        name: 'price',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '退保数量',
                        labelWidth: '70%',
                        name: 'withdraw',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '续保数量',
                        labelWidth: '70%',
                        name: 'xubaonum',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '续保电梯平均单价',
                        labelWidth: '70%',
                        name: 'xubaoprice',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '续保总金额',
                        labelWidth: '70%',
                        name: 'xubaocount',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '到期电梯数量',
                        labelWidth: '70%',
                        name: 'timeoutnum',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '到期电梯平均单价',
                        labelWidth: '70%',
                        name: 'timeprice',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '到期电梯总金额',
                        labelWidth: '70%',
                        name: 'timeoutcount',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '新签电梯数量',
                        labelWidth: '70%',
                        name: 'newnum',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '新签电梯平均单价',
                        labelWidth: '70%',
                        name: 'newprice',
                        readOnly: true
                    },
                    {
                        xtype: 'textfield',
                        clearIcon: false,
                        label: '新签电梯总金额',
                        labelWidth: '70%',
                        name: 'newcount',
                        readOnly: true
                    }
                ]
            }
        ]
    }

});